---
- name: Install postgres
  ansible.builtin.import_tasks: setup.postgres.yml

- name: Install Odoo
  ansible.builtin.import_tasks: setup.odoo.yml

- name: Configure Odoo
  ansible.builtin.import_tasks: configure.odoo.yml
