---
- name: Install namespace
  kubernetes.core.k8s:
    template:
      - path: templates/ns.yml.j2

- name: Add stable chart repo
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: https://charts.bitnami.com/bitnami
    force_update: true

- name: Install Postgres w/ Helm
  kubernetes.core.helm:
    name: "{{ k8s__odoo_community__db__name }}"
    chart_ref: bitnami/postgresql
    release_namespace: "{{ k8s__odoo_community__namespace }}"
    create_namespace: false
    wait: true
    values:
      primary:
        # will boost performances
        resourcesPreset: "xlarge"
        livenessProbe:
          # postgres might not respond under heavy load, which is frequent with odoo.
          # A livenessProbe that fails would restart service automatically, behavior which we do not want
          enabled: false
      auth:
        #
        postgresPassword: "{{ k8s__odoo_community__db__config__admin_password }}"
        # we must use defaults of Odoo if we want database to be automatically setup at first launch
        username: "{{ k8s__odoo_community__db__config__username }}"
        password: "{{ k8s__odoo_community__db__config__password }}"
        database: "{{ k8s__odoo_community__db__config__db_name }}"

- name: Add server definition for pgadmin
  tags: [pgadmin]
  when: k8s__odoo_community__add_server_definitions_into_pgadmin
  ansible.builtin.include_role:
    name: utilities__pgadmin
    tasks_from: add_server_definition
  vars:
    utilities__pgadmin__add_server_definition__id: odoo
    utilities__pgadmin__add_server_definition__name: Odoo
    utilities__pgadmin__add_server_definition__host: "{{ k8s__odoo_community__db__config__host }}"
    utilities__pgadmin__add_server_definition__maintenance_db: "{{ k8s__odoo_community__db__config__db_name }}"
    utilities__pgadmin__add_server_definition__username: "{{ k8s__odoo_community__db__config__username }}"
    utilities__pgadmin__add_server_definition__password: "{{ k8s__odoo_community__db__config__password }}"
