---
- name: Install prerequisites to use "community.postgresql.postgresql_query"
  ansible.builtin.apt:
    state: present
    update_cache: true
    package:
      - postgresql
      - libpq-dev
      - python3-psycopg2

- name: Create Database for SAML
  community.postgresql.postgresql_db:
    login_password: "{{ k8s__calcom__postgres__db_password }}"
    login_host: "{{ k8s__calcom__postgres__internal_hostname }}"
    name: "{{ k8s__calcom__saml_db_name }}"
