---
- name: Install prerequisites to use "community.postgresql.postgresql_query"
  ansible.builtin.apt:
    state: present
    update_cache: true
    package:
      - postgresql
      - libpq-dev
      - python3-psycopg2

- name: Create admin user
  community.postgresql.postgresql_query:
    db: "{{ db_name }}"
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    query: >
      UPDATE users
      SET password = crypt('{{ new_password }}', gen_salt('bf'))
      WHERE email = '{{ admin_email }}';
