---
- name: Run PipX w/ requisites
  community.general.pipx:
    state: inject
    name: ansible-core # name as used in pipx install (that installed ansible bin)
    inject_packages:
      - botocore
      - boto3

- name: Wait for the pod to be running state
  ansible.builtin.command: |
    kubectl get pod myminio-pool-0-0 -n minio-tenant -o jsonpath='{.status.phase}'
  register: pod_status
  until: pod_status.stdout == "Running"
  changed_when: pod_status.rc != 0
  retries: 10
  delay: 10

- name: Create default bucket
  amazon.aws.s3_bucket:
    access_key: "{{ minio__access_key_id }}"
    secret_key: "{{ minio__secret_access_key }}"
    #
    name: "{{ minio__tenant__backup_storage__bucket_name }}"
    endpoint_url: "{{ minio__tenant__s3_url }}" # HTTPS REQUIRED !
    validate_certs: false # ignore self signed certificates
    region: "{{ minio__tenant__backup_storage__bucket_region }}"
