---
- name: Add stable chart repo
  kubernetes.core.helm_repository:
    name: minio-operator
    repo_url: https://operator.min.io

- name: Install Zero-Trust configuration
  kubernetes.core.k8s:
    state: present
    template:
      - path: templates/operator/caa.yml.j2

- name: Install minIO operator w/ Helm
  kubernetes.core.helm:
    name: operator
    chart_ref: minio-operator/operator
    release_namespace: minio-operator
    create_namespace: true
    values:
      operator:
        replicaCount: 1
      console:
        ingress:
          enabled: true
          ingressClassName: "{{ ingress_nginx_class }}"
          host: "{{ k8s__minio__external_hostname }}"
          annotations:
            # when using Cloudflare's proxied DNS record
            nginx.ingress.kubernetes.io/ssl-redirect: "false"
            cert-manager.io/cluster-issuer: "{{ org_ca_name }}"
            nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
            #
            external-dns.alpha.kubernetes.io/hostname: "{{ k8s__minio__external_hostname }}"
            external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
            #
            ingress-dashboard/title: Minio Operator
            ingress-dashboard/description: Manage MinIO tenants of our organization
            ingress-dashboard/logo-url: /favicon.ico
            ingress-dashboard/assume-tls: "true"
            ingress-dashboard/hide: "false"

- name: Get Token
  register: minio_token
  ansible.builtin.shell: |
    set -o pipefail
    kubectl get secret/console-sa-secret -n minio-operator -o json | jq -r ".data.token" | base64 -d
  changed_when: minio_token.rc != 0

- name: Save Token
  ansible.builtin.copy:
    content: "{{ minio_token.stdout }}"
    dest: "{{ generated_creds_dir }}/minio-console-token.txt"
    mode: "0775"
