---
- name: Store token for account
  vars:
    namespace: "{{ argo_cd__namespace }}"
    secret_name: "{{ argo_cd__jwt_tokens_secret }}"
  block:
    - name: Generate new token
      register: token
      ansible.builtin.uri:
        url: "{{ k8s__argo_cd_cluster_api_url }}/account/{{ item.username }}/token"
        validate_certs: false
        method: POST
        headers:
          Authorization: "Bearer {{ bearer }}"
          Content-Type: "application/json"
        body_format: json
        body:
          expiresIn: 0 # never expires
    - name: Store pair into an object
      ansible.builtin.set_fact:
        pair: "{ '{{ item.username }}': '{{ token.json.token }}' }"
    - name: Save into Secret, override existing value
      kubernetes.core.k8s:
        state: present
        api_version: v1
        kind: Secret
        namespace: "{{ namespace }}"
        name: "{{ secret_name }}"
        definition:
          stringData: "{{ pair }}"
