---
- name: Install App of apps repository to ArgoCD
  tags: [apps, argocd]
  kubernetes.core.k8s:
    template:
      - path: templates/applications/app-of-apps.secret.yml.j2
      - path: templates/applications/app-of-apps.yml.j2
