---
- name: Get ArgoCD authentication token
  ansible.builtin.uri:
    url: "{{ k8s__argo_cd_cluster_api_url }}/session"
    validate_certs: false
    method: POST
    body_format: json
    body:
      username: "admin"
      password: "{{ argocd__admin_password }}"
  register: argocd_auth_response

##
- name: Generate tokens into Secret
  ansible.builtin.include_tasks: _helper.generate-token.yml
  vars:
    bearer: "{{ argocd_auth_response.json.token }}"
  loop:
    - username: "{{ argocd__account_for__github_syncer }}"
    - username: "{{ argocd__account_for__argo_watcher }}"
