---
- name: Install Secret
  tags: [image-updater]
  kubernetes.core.k8s:
    template:
      - path: templates/image-updater/secret.yml.j2

- name: Install ArgoCD Image Updater w/ Helm
  tags: [image-updater]
  kubernetes.core.helm:
    name: argocd-image-updater
    chart_ref: argo/argocd-image-updater
    release_namespace: "{{ argo_cd__namespace }}"
    create_namespace: false
    wait: false
    values:
      volumeMounts:
        - name: crt
          mountPath: /etc/ssl/certs/ca-certificates.crt # only way to allow our CA to be acked for classic HTTPS calls
          subPath: ca.crt
      volumes:
        - name: crt
          secret:
            secretName: "{{ cert_manager__org__root_ca__bundle }}"
      # extraArgs:
      #   - --interval
      #   - 1m0s
      #   - --loglevel
      #   - trace
      config:
        registries:
          - name: Docker Hub
            prefix: docker.io
            api_url: https://registry-1.docker.io
            defaultns: library
          - name: Harbor - {{ iac__root_domain }} Private Registry
            prefix: "{{ harbor__internal_hostname__registry_v2 }}"
            api_url: "{{ harbor__internal_hostname__registry_v2__url }}"
            defaultns: "{{ harbor__org_project_name }}"
            # https://argocd-image-updater.readthedocs.io/en/stable/configuration/registries/#configuration-format
            credentials: secret:{{ argo_cd__namespace }}/argocd-image-updater#PRIVATE_REGISTRY_V2_AUTH
            # insecure: true
            # default: true
