---
- name: Install ArgoCD Image Updater w/ Helm
  tags: [image-updater]
  kubernetes.core.helm:
    name: argocd-image-updater
    chart_ref: argo/argocd-image-updater
    release_namespace: "{{ k8s__argo_cd__namespace }}"
    create_namespace: false
    wait: false
    values:
      extraArgs:
        - --interval
        - 30s
      config:
        registries:
          - name: Docker Hub
            prefix: docker.io
            api_url: https://registry-1.docker.io
            defaultns: library
          - name: Harbor - {{ iac__root_domain }} Private Registry
            api_url: http://{{ harbor__internal_hostname__registry_v2 }}
            prefix: "{{ harbor__internal_hostname__registry_v2 }}"
            # https://argocd-image-updater.readthedocs.io/en/stable/configuration/registries/#configuration-format
            credentials: secret:{{ k8s__argo_cd__namespace }}/argocd-image-updater#PRIVATE_REGISTRY_V2_AUTH
            insecure: true
            default: true
