---
- name: Add stable chart repo
  kubernetes.core.helm_repository:
    name: argo
    repo_url: https://argoproj.github.io/argo-helm

- name: Define CM params
  ansible.builtin.set_fact:
    cm:
      # Argo CD's externally facing base URL (optional). Required when configuring SSO
      url: "{{ k8s__argo_cd__external_hostname_url }}"
      # Enables application status badge feature
      statusbadge.enabled: true
    ### ACCOUNTS connection methods, only allow API key for Github Syncer
    cm_more: |
      {
        "accounts.{{ argocd_account_for_github_syncer }}": "apiKey",
        "accounts.{{ argocd_account_for_argo_watcher }}": "apiKey",
      }

- name: Define RBAC params
  ansible.builtin.set_fact:
    rbac:
      policy.default: "role:readonly"
      policy.csv: |
        p, role:syncer, applications, sync, */*, allow
        p, role:watcher, applications, get, */*, allow
        p, role:watcher, applications, sync, */*, allow

        g, {{ argocd_account_for_argo_watcher }}, role:watcher
        g, {{ argocd_account_for_github_syncer }}, role:syncer

- name: Define PARAMS params
  ansible.builtin.set_fact:
    params:
      server.insecure: true
      # Enable self-service notifications config. Used in conjunction with apps-in-any-namespace. (default "false")
      notificationscontroller.selfservice.enabled: false

- name: Install ArgoCD w/ Helm
  kubernetes.core.helm:
    name: argocd
    chart_ref: argo/argo-cd
    release_namespace: argocd
    create_namespace: true
    wait: true
    values:
      global:
        domain: "{{ k8s__argo_cd__external_hostname }}"
      notifications:
        argocdUrl: "{{ k8s__argo_cd__external_hostname_url }}"
        secret:
          items:
            github-privateKey: |
              {{ argocd_github_app_priv_key }}
        notifiers:
          service.github: |
            appID: "{{ argocd_github_app_app_id }}"
            installationID: "{{ argocd_github_app_installation_id }}"
            privateKey: $github-privateKey
        templates: "{{ lookup('ansible.builtin.file', 'templates/github-notifications/all.yaml.gotmpl') | from_yaml }}"
      configs:
        params: "{{ params }}"
        rbac: "{{ rbac }}"
        cm: "{{ cm | ansible.builtin.combine(cm_more) }}"
      certificate:
        enabled: false
      server:
        replicas: 1
        ingress:
          enabled: true
          ingressClassName: "{{ ingress_nginx_class }}"
          annotations:
            # when using Cloudflare's proxied DNS record
            nginx.ingress.kubernetes.io/ssl-redirect: "false"
            cert-manager.io/cluster-issuer: "{{ org_ca_name }}"
            nginx.ingress.kubernetes.io/ssl-passthrough: "true"
            nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
            #
            external-dns.alpha.kubernetes.io/hostname: "{{ k8s__argo_cd__external_hostname }}"
            external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
            #
            ingress-dashboard/title: ArgoCD
            ingress-dashboard/description: Automatize k8s app deployment through GitOps
            ingress-dashboard/logo-url: /assets/favicon/favicon-32x32.png
            ingress-dashboard/assume-tls: "true"
            ingress-dashboard/hide: "false"
          tls: false
      repoServer:
        replicas: 1
      applicationSet:
        replicas: 1
      controller:
        replicas: 1
