---
version: 3

images:
  base_image:
    name: quay.io/fedora/fedora:39

dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  system:
    - openssh-clients
    - sshpass
    # - yq
  galaxy:
    collections:
      - name: community.docker
      - name: kubernetes.core
      - name: ansible.posix
      - name: community.general
      - name: amazon.aws

# we use this yq and not system yq, since this one is more powerful
additional_build_steps:
  prepend_base:
    - ARG TARGETARCH
    - ARG TARGETOS
    - ADD https://github.com/mikefarah/yq/releases/download/v4.45.1/yq_${TARGETOS}_${TARGETARCH} /usr/bin/yq
    - RUN chmod +x /usr/bin/yq
