---
- name: Install Posthog proxy (middleware + services)
  kubernetes.core.k8s:
    template:
      - path: templates/ns.yml.j2
      - path: templates/middleware.yml.j2
      - path: templates/svc.yml.j2

- name: Define relay ingresses
  kubernetes.core.k8s:
    template:
      - path: templates/ingress.yml.j2
  loop: "{{ iac__all_domains }}"
  loop_control:
    loop_var: external_hostname
    label: "{{ k8s__posthog_proxy__subdomain }}.{{ external_hostname }}"
