---
###
- name: Install Helm
  community.general.snap:
    name:
      - helm
- name: Install helm-diff
  kubernetes.core.helm_plugin:
    plugin_path: https://github.com/databus23/helm-diff

###
- name: Update python's Kubernetes lib
  ansible.builtin.pip:
    extra_args: --break-system-packages --pre --upgrade
    name:
      - kubernetes
