---
# - name: Create Persistent Volume dir paths
#   ansible.builtin.file:
#     path: "{{ item }}"
#     state: directory
#     mode: '0755'
#   loop:
#     - "{{ prometheus_pv_path }}/{{ prometheus_alertmanager_pv_subpath }}"
#     - "{{ prometheus_pv_path }}/{{ prometheus_server_pv_subpath }}"

# - name: Install PVs
#   kubernetes.core.k8s:
#     state: present
#     template:
#       - path: 'templates/pv.yml.j2'
#   vars:
#     local_storage_class_name: local-storage

- name: Add stable chart repo
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Install Prometheus Stack w/ Helm
  vars:
    local_storage_class_name: local-storage
  kubernetes.core.helm:
    name: prometheus-stack
    chart_ref: prometheus-community/kube-prometheus-stack
    release_namespace: prometheus-stack
    create_namespace: true
    values:
      # alertmanager:
      #   persistence:
      #     size: "{{ prometheus_alertmanager_pv_size }}"
      # persistentVolume:
      #   mountPath: "{{ prometheus_pv_path }}"
      #   size: "{{ prometheus_server_pv_size }}"
      #   storageClass: "{{ local_storage_class_name }}"
      grafana:
        service:
          type: LoadBalancer
        ingress:
          enabled: true
          ingressClassName: "{{ ingress_nginx_class }}"
          annotations:
            # Will be handled by Cloudflare proxy
            nginx.ingress.kubernetes.io/ssl-redirect: "false"
            cert-manager.io/cluster-issuer: "selfsigned" # "{{ cluster_issuer_name }}"
          hosts:
            - graphana.{{ root_domain }}
      prometheus:
        service:
          type: LoadBalancer
        ingress:
          enabled: true
          ingressClassName: "{{ ingress_nginx_class }}"
          annotations:
            # Will be handled by Cloudflare proxy
            nginx.ingress.kubernetes.io/ssl-redirect: "false"
            cert-manager.io/cluster-issuer: "selfsigned" # "{{ cluster_issuer_name }}"
          hosts:
            - prometheus.{{ root_domain }}
