---
# inspired by https://raw.githubusercontent.com/posthog/posthog/HEAD/bin/deploy-hobby
sidekick__posthog__registry_url: posthog/posthog
# https://github.com/PostHog/posthog/issues/29706
sidekick__posthog__posthog_app_tag: 1b49d06a5b0a41021c4976a74d1bb1db0f2614a3
sidekick__posthog__domain: posthog.{{ iac__root_domain }}
sidekick__posthog__sentry_dsn: "{{ posthog_sentry_project_dns }}"
sidekick__posthog__encryption_salt_keys: "{{ posthog_encryption_salt_keys }}"
sidekick__posthog__posthog_secret: "{{ posthog_secret }}"

#
sidekick__posthog__install_dir: "/opt/iac_posthog"
sidekick__posthog__github_repo: https://github.com/PostHog/posthog.git
sidekick__posthog__github_files_to_dl:
  ["docker-compose.hobby.yml", "docker-compose.base.yml"]

# https://posthog.com/docs/self-host/configure/environment-variables
sidekick__posthog__more_env_vars:
  IS_BEHIND_PROXY: "True"
  # TRUSTED_PROXIES: "<IPs>"
  TRUST_ALL_PROXIES: "True"
  #
  EMAIL_ENABLED: "True"
  EMAIL_HOST: "{{ docker_mailserver__external_hostname }}"
  EMAIL_PORT: "587"
  EMAIL_DEFAULT_FROM: "{{ iac__donotreply_email }}"
  EMAIL_HOST_USER: "{{ iac__donotreply_username }}"
  EMAIL_HOST_PASSWORD: "{{ iac__donotreply_password }}"
  EMAIL_USE_TLS: "True"
  EMAIL_USE_SSL: "False"

#
sidekick__posthog__traefik_network: "{{ sidekick_traefik_external_network }}"

sidekick__posthog__traefik_exposed__web:
  - traefik.enable=true
  - traefik.docker.network={{ sidekick__posthog__traefik_network }}
  - traefik.http.routers.posthog-web.rule=Host(`${DOMAIN}`)
  - traefik.http.routers.posthog-web.entrypoints=web
  - traefik.http.services.posthog-web.loadbalancer.server.port=8000
sidekick__posthog__traefik_exposed__livestream:
  - traefik.enable=true
  - traefik.docker.network={{ sidekick__posthog__traefik_network }}
  - traefik.http.routers.posthog-livestream.rule=Host(`${DOMAIN}`)
  - traefik.http.routers.posthog-livestream.entrypoints=web
  - traefik.http.services.posthog-livestream.loadbalancer.server.port=8666
