---
# inspired by https://raw.githubusercontent.com/posthog/posthog/HEAD/bin/deploy-hobby
sidekick__posthog__registry_url: posthog/posthog
# https://github.com/PostHog/posthog/issues/29706
sidekick__posthog__posthog_app_tag: latest # 6bda8cb363ae86e6fb925137315ae035df937a8e
sidekick__posthog__domain: posthog.{{ iac__root_domain }}
sidekick__posthog__sentry_dsn: "{{ posthog_sentry_project_dns }}"
sidekick__posthog__encryption_salt_keys: "{{ posthog_encryption_salt_keys }}"
sidekick__posthog__posthog_secret: "{{ posthog_secret }}"
sidekick__posthog__organization_name: "{{ iac__ldap_org }}"

#
sidekick__posthog__install_dir: "/opt/iac_posthog"
sidekick__posthog__web_container: "{{ sidekick__posthog__install_dir | basename }}-web-1"
sidekick__posthog__github_repo: https://github.com/PostHog/posthog.git
sidekick__posthog__github_files_to_dl:
  ["docker-compose.hobby.yml", "docker-compose.base.yml"]

# https://posthog.com/docs/self-host/configure/environment-variables
sidekick__posthog__more_env_vars:
  NEW_CAPTURE_ENDPOINT: "/e/" # see https://github.com/PostHog/posthog/issues/28804
  IS_BEHIND_PROXY: "true"
  # TRUSTED_PROXIES: "<IPs>"
  TRUST_ALL_PROXIES: "true"
  # Below is outdated (by official docs)
  # EMAIL_ENABLED: "true"
  # EMAIL_HOST: "{{ docker_mailserver__external_hostname }}"
  # EMAIL_PORT: "587"
  # EMAIL_DEFAULT_FROM: "{{ iac__donotreply_email }}"
  # EMAIL_HOST_USER: "{{ iac__donotreply_username }}"
  # EMAIL_HOST_PASSWORD: "{{ iac__donotreply_password }}"
  # EMAIL_USE_TLS: "true"
  # EMAIL_USE_SSL: "false"

# must use Python single quotes for string and Uppercase bool
sidekick__posthog__mail_config:
  EMAIL_ENABLED: "True"
  EMAIL_HOST: "'{{ docker_mailserver__external_hostname }}'"
  EMAIL_PORT: "587"
  EMAIL_DEFAULT_FROM: "'{{ iac__donotreply_email }}'"
  EMAIL_HOST_USER: "'{{ iac__donotreply_username }}'"
  EMAIL_HOST_PASSWORD: "'{{ iac__donotreply_password }}'"
  EMAIL_USE_TLS: "True"
  EMAIL_USE_SSL: "False"

##
##
##

#
sidekick__posthog__traefik_network: "{{ sidekick_traefik_external_network }}"

#
sidekick__posthog__traefik_exposed__web:
  - traefik.enable=true
  - traefik.docker.network={{ sidekick__posthog__traefik_network }}
  - traefik.http.routers.posthog-web.rule=Host(`${DOMAIN}`)
  - traefik.http.routers.posthog-web.middlewares=testheader@docker
  - traefik.http.routers.posthog-web.entrypoints=web
  - traefik.http.services.posthog-web.loadbalancer.server.port=8000
  - traefik.http.middlewares.testheader.headers.accesscontrolalloworiginlist=*

#
sidekick__posthog__traefik_exposed__livestream:
  - traefik.enable=true
  - traefik.docker.network={{ sidekick__posthog__traefik_network }}
  - traefik.http.routers.posthog-livestream.rule=Host(`${DOMAIN}`)
  - traefik.http.routers.posthog-livestream.middlewares=testheader@docker
  - traefik.http.routers.posthog-livestream.entrypoints=web
  - traefik.http.services.posthog-livestream.loadbalancer.server.port=8666
  - traefik.http.middlewares.testheader.headers.accesscontrolalloworiginlist=*
