---
sidekick__posthog__install_dir: "/opt/posthog"
sidekick__posthog__origin: posthog.{{ iac__root_domain }}
sidekick__posthog__site_url: "https://{{ sidekick__posthog__origin }}"
sidekick__posthog__version_tag: latest

# Script de déploiement PostHog
sidekick__posthog__deploy_script_url: "https://raw.githubusercontent.com/posthog/posthog/HEAD/bin/deploy-hobby"
sidekick__posthog__deploy_script_dest: "{{ sidekick__posthog__install_dir }}/deploy-hobby"
