---
- name: Get whole config
  ansible.builtin.set_fact:
    ldap_config: "{{ iac__ldap__groups | from_yaml }}"

- name: Create root OU
  community.general.ldap_entry:
    server_uri: "{{ openldap_stack__ldap_uri }}"
    bind_dn: "{{ iac__ldap__admin__bind_dn }}"
    bind_pw: "{{ iac__ldap__admin__bind_pw }}"
    #
    dn: "ou={{ utilities__ldap_org_unit }},{{ iac__ldap__root_dc }}"
    objectClass: organizationalUnit
    attributes:
      ou: "{{ utilities__ldap_org_unit }}"

- name: Create groups, or make sure they exist
  community.general.ldap_entry:
    server_uri: "{{ openldap_stack__ldap_uri }}"
    bind_dn: "{{ iac__ldap__admin__bind_dn }}"
    bind_pw: "{{ iac__ldap__admin__bind_pw }}"
    #
    dn: "cn={{ item }},ou={{ utilities__ldap_org_unit }},{{ iac__ldap__root_dc }}"
    objectClass:
      - groupOfNames
    attributes:
      cn: "{{ item }}"
      member: "" # defaults to no members, will fill them later on. Wont override existing
  loop: "{{ ldap_config | json_query(utilities__ldap_org_unit + '[*].groupName') }}"

- name: Add members to this group
  community.general.ldap_attrs:
    server_uri: "{{ openldap_stack__ldap_uri }}"
    bind_dn: "{{ iac__ldap__admin__bind_dn }}"
    bind_pw: "{{ iac__ldap__admin__bind_pw }}"
    #
    dn: "cn={{ item.groupName }},ou={{ utilities__ldap_org_unit }},{{ iac__ldap__root_dc }}"
    attributes:
      member: "{{ item.members }}"
    state: present # 'exact' would remove all that are not in this, 'present' is the way to go
  loop: "{{ ldap_config | json_query(utilities__ldap_org_unit + '[*]') }}"
