#
# WHERE GLOBAL-ISH, default IAC infos regarding services are stored
#
---
#######################
### MIGHT CUSTOMIZE ###
#######################

# where should ALL the persistent volumes of IaC be installed
iac__pv_path_root: /var/k8s-data

# SMTP / IMAP servers hard-requires + autoconfig soft-requires unproxied (NO CLOUDFLARE !) certificates
# @info refers to any of "roles/k8.cert-manager/templates/issuer-*.yml.j2" metadata.name which will issue certificates
# CAREFUL ! In production, 50 requested certificates per week for letsencrypt ! (https://letsencrypt.org/docs/rate-limits/)
iac__unproxied_certificate_issuer: letsencrypt-prod # zerossl-prod

# catch all, smtp / imap TLD on the root_domain
docker_mailserver__third_level_domain: mail

#
iac__postmaster_username: postmaster
iac__donotreply_username: donotreply
iac__donotreply_name: Do Not Reply

# Root OU : groupOfNames : [users CN]
iac__ldap__groups: |-
  argocd:
    - groupName: admin
      members:
        - cn={{ iac__postmaster_username }}

#
sentry__usermail: "{{ iac__postmaster_username }}@{{ iac__root_domain }}"

# minimum 3 chars
minio__tenant__username: admin

#
matomo__admin_username: admin

#
argocd__app_of_apps__repo_name: argocd-repository # github repo name under organization, containing app of apps argocd manifest

#
listmonk__static_dir__repo_name: listmonk-static # github repo name under organization, containing listmonk static dir
listmonk__admin_username: admin
listmonk__logo_url: https://{{ iac__root_domain }}/logo.png
listmonk__favicon_url: https://{{ iac__root_domain }}/logo.png

#
harbor__registry_username: "{{ iac__github_org | lower }}" # must always be lowercase

############################
### SHOULD NOT CUSTOMIZE ###
############################

# MUST be the same as in "ansible/inventories/production/hosts.yaml"
iac__master_node_name: node1 # default

#
iac__ingress_class_name: traefik

#
cert_manager__namespace: cert-manager
cert_manager__org__issuer: selfsigned # dummy issuer; issues Org Root CA + dummy certificates
cert_manager__org__root_ca: "{{ iac__root_domain }}-root-ca"
cert_manager__org__root_ca__bundle: "{{ cert_manager__org__root_ca }}.bundle" # default, bundled CAs for a system to trust, including our own root cert

# where generated passwords and other tokens are to be stored while generating services
iac__generated_creds_dir: "{{ playbook_dir ~ '/../../creds' }}"

#
iac__github_org_url: https://github.com/{{ iac__github_org }}

# default storage class
iac__local_storage__class_name: local-storage

# where should the persistent volume created for X service, store its data on node
iac__pv_path__portainer: "{{ iac__pv_path_root }}/portainer"
iac__pv_path__docker_mailserver: "{{ iac__pv_path_root }}/mailserver"
iac__pv_path__hc_vault: "{{ iac__pv_path_root }}/hc-vault"
iac__pv_path__roundcube: "{{ iac__pv_path_root }}/roundcube"
iac__pv_path__harbor: "{{ iac__pv_path_root }}/harbor"
iac__pv_path__openldap: "{{ iac__pv_path_root }}/openldap"
iac__pv_path__listmonk__db: "{{ iac__pv_path_root }}/listmonk/db"
iac__pv_path__listmonk__uploads: "{{ iac__pv_path_root }}/listmonk/uploads"
iac__pv_path__matomo__db: "{{ iac__pv_path_root }}/matomo/db"
iac__pv_path__matomo__app: "{{ iac__pv_path_root }}/matomo/app"
iac__pv_path__github_arc__cache: "{{ iac__pv_path_root }}/gha-cache"
iac__pv_path__buildkit__cache: "{{ iac__pv_path_root }}/buildkit-cache"
iac__pv_path__ez_appointments: "{{ iac__pv_path_root }}/ez-appointments"
iac__pv_path__odoo: "{{ iac__pv_path_root }}/odoo"

#
github_arc__buildkit__remote_socket: buildkit-buildkit-service.arc-buildkit:1234
github_arc__buildkit__local_mount_path: /cache

#
minio__access_key_id: "{{ minio__tenant__username }}"
minio__tenant__s3_url: https://minio.minio-tenant:443
minio__tenant__backup_storage__bucket_name: default-backups # https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html
minio__tenant__backup_storage__bucket_region: minio

#
listmonk__from_email: "{{ listmonk__site_name }} <{{ iac__postmaster_email }}>"

#
harbor__namespace: harbor
harbor__name: harbor
harbor__sld: registry
harbor__internal_hostname__registry_v2: "{{ harbor__name }}-core.{{ harbor__namespace }}.svc.cluster.local" # we need the service that responds to /v2/ path
harbor__internal_hostname__registry_v2__url: https://{{ harbor__internal_hostname__registry_v2 }}
harbor__admin_username: admin
harbor__org_project_name: "{{ iac__github_org | lower }}"

#
docker_mailserver__namespace: docker-mailserver
docker_mailserver__server_hostname: docker-mailserver
docker_mailserver__server_label: docker-mailserver
docker_mailserver__users_group_name: email-users
docker_mailserver__users_group_description: "{{ iac__root_domain }}'s users that have a mail account behind a password"
# Email users (possibly POSTFIX + DOVECOT, eg sending AND receiving email)
# SHOULD MATCH GID of docker-mailserver's dovecot id group, which create folder structure for IMAP users
docker_mailserver__users_group_id: 5000

#
docker_mailserver__internal_smtp_server: "{{ docker_mailserver__server_hostname }}.{{ docker_mailserver__namespace }}.svc.cluster.local"
docker_mailserver__internal_smtp_preferred_port: 587

#
openldap_stack__namespace: openldap-stack
openldap_stack__ldap_server_hostname: openldap
openldap_stack__ldap_internal_hostname: "{{ openldap_stack__ldap_server_hostname }}.{{ openldap_stack__namespace }}.svc.cluster.local"
openldap_stack__ldap_uri: ldap://{{ openldap_stack__ldap_internal_hostname }}/
openldap_stack__dc_query_string: "{{ iac__root_domain | split('.') | map('regex_replace', '^(.*)$', 'dc=\\1') | list | join(',') }}"
openldap_stack__ldap_admin_user: admin
openldap_stack__ldap_admin_cn: cn={{ openldap_stack__ldap_admin_user }},{{ openldap_stack__dc_query_string }}

#
argo_cd__namespace: argocd
argocd__account_for__github_syncer: github-syncer
argocd__account_for__argo_watcher: watcher
argo_cd__jwt_tokens_secret: accounts-immortal-jwt
argocd__project_name: default

#
docker_mailserver__external_hostname: "{{ docker_mailserver__third_level_domain }}.{{ iac__root_domain }}"

#
iac__postmaster_email: "{{ iac__postmaster_username }}@{{ iac__root_domain }}"
iac__donotreply_email: "{{ iac__donotreply_username }}@{{ iac__root_domain }}"

#
cf_zto__namespace: zero-trust-system
cf_zto__ldap_policy__access_group_id: ldap-users
cf_zto__ldap_policy__name: Allow {{ iac__root_domain }} LDAP Users

#
kyverno__oc_label_as_env__version: BUILDX_OC_LABEL__VERSION # tag
kyverno__oc_label_as_env__revision: BUILDX_OC_LABEL__REVISION # commit
