#
# WHERE GLOBAL-ISH, default IAC infos regarding services are stored
#
---
#######################
### MIGHT CUSTOMIZE ###
#######################

# where should ALL the persistent volumes of IaC be installed
iac__pv_path_root: /var/k8s-data

# SMTP / IMAP servers hard-requires + autoconfig soft-requires unproxied (NO CLOUDFLARE !) certificates
# @info refers to any of "roles/k8.cert-manager/templates/issuer-*.yml.j2" metadata.name which will issue certificates
# CAREFUL ! In production, 50 requested certificates per week for letsencrypt ! (https://letsencrypt.org/docs/rate-limits/)
iac__unproxied_certificate_issuer: letsencrypt-prod # zerossl-prod

# catch all, smtp / imap TLD on the root_domain
docker_mailserver__third_level_domain: mail

#
iac__postmaster_username: postmaster
iac__donotreply_username: donotreply

#
sentry__usermail: "{{ iac__postmaster_username }}@{{ iac__root_domain }}"

# minimum 3 chars
minio__tenant__username: admin

#
matomo__admin_username: admin

#
argocd__app_of_apps__repo_name: argocd-repository # github repo name under organization, containing app of apps argocd manifest

#
listmonk__static_dir__repo_name: listmonk-static # github repo name under organization, containing listmonk static dir
listmonk__admin_username: admin
listmonk__logo_url: https://{{ iac__root_domain }}/logo.png
listmonk__favicon_url: https://{{ iac__root_domain }}/logo.png

############################
### SHOULD NOT CUSTOMIZE ###
############################

# MUST be the same as in "ansible/inventories/production/hosts"
iac__master_node_name: node1

# MUST be the same as "group_vars/k8s_cluster/addons".iac__ingress_nginx_class
iac__ingress_nginx_class: nginx

#
cert_manager__org_ca__name: selfsigned
cert_manager__org_ca__cert_secret_name: "trust-manager.{{ cert_manager__org_ca__name }}"
cert_manager__trust_managed_namespaces: [arc-runners]


# where generated passwords and other tokens are to be stored while generating services
iac__generated_creds_dir: "{{ playbook_dir ~ '/../../creds' }}"

#
iac__github_org_url: https://github.com/{{ iac__github_org }}

# default storage class
iac__local_storage__class_name: local-storage

# where should the persistent volume created for X service, store its data on node
iac__pv_path__portainer: "{{ iac__pv_path_root }}/portainer"
iac__pv_path__docker_mailserver: "{{ iac__pv_path_root }}/mailserver"
iac__pv_path__hc_vault: "{{ iac__pv_path_root }}/hc-vault"
iac__pv_path__roundcube: "{{ iac__pv_path_root }}/roundcube"
iac__pv_path__registry: "{{ iac__pv_path_root }}/registry"
iac__pv_path__openldap: "{{ iac__pv_path_root }}/openldap"
iac__pv_path__listmonk__db: "{{ iac__pv_path_root }}/listmonk/db"
iac__pv_path__listmonk__uploads: "{{ iac__pv_path_root }}/listmonk/uploads"
iac__pv_path__matomo__db: "{{ iac__pv_path_root }}/matomo/db"
iac__pv_path__matomo__app: "{{ iac__pv_path_root }}/matomo/app"
iac__pv_path__github_arc__cache: "{{ iac__pv_path_root }}/gha-cache"
iac__pv_path__buildkit__cache: "{{ iac__pv_path_root }}/buildkit-cache"

#
github_arc__buildkit__remote_socket: buildkit-buildkit-service.arc-buildkit:1234
github_arc__buildkit__local_mount_path: /cache

#
minio__access_key_id: "{{ minio__tenant__username }}"
minio__tenant__s3_url: https://minio.minio-tenant:443
minio__tenant__backup_storage__bucket_name: default-backups # https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html
minio__tenant__backup_storage__bucket_region: minio

#
listmonk__from_email: "{{ listmonk__site_name }} <{{ iac__postmaster_email }}>"

#
registry__hostname: registry.kube-system
registry__default_push_user: "{{ iac__github_org | lower }}" # must always be lowercase

#
openldap_stack__namespace: openldap-stack
openldap_stack__ldap_server_hostname: openldap
openldap_stack__ldap_uri: ldap://{{ openldap_stack__ldap_server_hostname }}.{{ openldap_stack__namespace }}/
openldap_stack__dc_query_string: "{{ iac__root_domain | split('.') | map('regex_replace', '^(.*)$', 'dc=\\1') | list | join(',') }}"
openldap_stack__ldap_admin_user: admin
openldap_stack__ldap_admin_cn: cn={{ openldap_stack__ldap_admin_user }},{{ openldap_stack__dc_query_string }}

#
argocd__account_for__github_syncer: github-syncer
argocd__account_for__argo_watcher: watcher

#
docker_mailserver__external_hostname: "{{ docker_mailserver__third_level_domain }}.{{ iac__root_domain }}"

#
iac__postmaster_email: "{{ iac__postmaster_username }}@{{ iac__root_domain }}"
iac__donotreply_email: "{{ iac__donotreply_username }}@{{ iac__root_domain }}"
