---
# - name: Get ArgoCD authentication token
#   ansible.builtin.uri:
#     url: "{{ k8s__argocd__api_url }}/session"
#     validate_certs: false
#     method: POST
#     body_format: json
#     body:
#       username: "admin"
#       password: "{{ argocd__admin_password }}"
#   register: argocd_auth_response

- name: Store token for account
  vars:
    argocd_namespace: "{{ argocd__namespace }}"
    secret_name: "{{ argocd__jwt_tokens_secret }}"
  block:
    - name: Generate new token
      register: token
      ansible.builtin.uri:
        url: "{{ k8s__argocd__api_url }}/account/{{ item.username }}/token"
        validate_certs: false
        method: POST
        headers:
          Authorization: "Bearer {{ bearer }}"
          Content-Type: "application/json"
        body_format: json
        body:
          expiresIn: 0 # never expires
    - name: Store pair into an object
      ansible.builtin.set_fact:
        pair: "{ '{{ item.username }}': '{{ token.json.token }}' }"
    - name: Save into Secret, override existing value
      kubernetes.core.k8s:
        api_version: v1
        kind: Secret
        namespace: "{{ argocd_namespace }}"
        name: "{{ secret_name }}"
        definition:
          stringData: "{{ pair }}"
