---
- name: Define or create default Storage Class
  kubernetes.core.k8s:
    state: present
    template:
      - path: templates/sc.yml.j2

#
- name: Add helm diff plugin
  kubernetes.core.helm_plugin:
    plugin_path: https://github.com/databus23/helm-diff
    state: present # cannot use "latest" since we use git repo as source

# https://github.com/siarheidudko/webmin-under-kubernetes-ingress
- name: Patch external trafic policy of ingress controller service
  kubernetes.core.k8s:
    state: patched
    kind: Service
    name: ingress-nginx
    namespace: ingress-nginx
    definition:
      spec:
        externalTrafficPolicy: "Local"
