---
- name: Add stable chart repo
  kubernetes.core.helm_repository:
    name: andrcuns
    repo_url: https://andrcuns.github.io/charts

# https://github.com/moby/buildkit/tree/master/examples/kubernetes
- name: Install Buildkit Runners
  kubernetes.core.helm:
    name: buildkit
    chart_ref: andrcuns/buildkit-service
    release_namespace: "{{ k8s__github_arc__buildkit_ns }}"
    create_namespace: true
    wait: true
    values:
      buildkitdToml: |
        insecure-entitlements = [ "network.host", "security.insecure" ]

        [registry."{{ harbor__internal_hostname }}"]
        http = false
        insecure = true
