---
- name: Install ARC
  kubernetes.core.helm:
    name: arc
    chart_ref: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
    release_namespace: "{{ k8s__github_arc_systems_ns }}"
    create_namespace: true

- name: Generate Access Token
  ansible.builtin.set_fact:
    github_arc_access_token: "{{ lookup('password', '/dev/null chars=ascii_letters,digit length=32', seed=inventory_hostname) | lower }}"

- name: Create Persistent Volume dir path
  ansible.builtin.file:
    path: "{{ iac__pv_path__github_arc__cache }}"
    state: directory
    mode: "0755"

- name: Install local cache server + access method to it for runners set
  kubernetes.core.k8s:
    state: present
    template:
      - path: templates/local-cache-runner/sc.yml
      - path: templates/local-cache-runner/pv.yml
      - path: templates/local-cache-runner/config.yml
      - path: templates/local-cache-runner/secret.yml
      - path: templates/local-cache-runner/deploy.yml
      - path: templates/local-cache-runner/service.yml
      - path: templates/runner-set/ns.yml.j2
      - path: templates/runner-set/gha-cache-access.yml.j2
