---
##
## Generate DKIM
##

- name: Wait until Mailserver pod is created (and Ready !)
  until: >
    docker_mailserver_pod_search.resources is defined and
    docker_mailserver_pod_search.resources | length > 0 and
    docker_mailserver_pod_search.resources[0].status.phase == "Running"
  retries: 20
  delay: 5
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: "{{ docker_mailserver__namespace }}"
    label_selectors:
      - app={{ docker_mailserver__server_label }}
  register: docker_mailserver_pod_search

- name: Generate DKIM for domains, from pod
  kubernetes.core.k8s_exec:
    namespace: "{{ docker_mailserver__namespace }}"
    pod: "{{ docker_mailserver_pod_search.resources[0].metadata.name }}"
    command: setup config dkim domain '{{ iac__all_domains | join(",") }}'
  register: dkim_generation_cmd
  notify:
    - DKIM - Reboot mailserver

- name: Extract DKIM TXT (1/2)
  ansible.builtin.slurp:
    src: "{{ k8s__docker_mailserver__dkim_file_path }}"
  register: dkim_content

- name: Extract DKIM TXT (2/2)
  ansible.builtin.set_fact:
    dkim_txt: "{{ dkim_content['content'] | b64decode | regex_replace('[\n\r]', '') |
      regex_replace('.*\"(v=DKIM1.*?)\"\\s+\"(.*?)\"\\s+\"(.*?)\".*', '\\1\\2\\3') }}"

# - name: Display formatted DKIM
#   ansible.builtin.debug::
#     var: dkim_txt

##
## Deploy DNS Rules (non-provider agnostic !)
## (dns-external lacks providers support (cloudflare in particular...) with DNSEndpoint CRD)
##

- name: Configure Cloudflare DNS zones
  ansible.builtin.include_tasks: _helper.cloudflare-dns.yml
  vars:
    dkim: "{{ dkim_txt }}"
  loop: "{{ iac__all_domains }}"
  loop_control:
    loop_var: dnsZone
