---
# - name: Setup Server
#   ansible.builtin.import_tasks: setup-server.yml

# - name: Configure DNS records
#   ansible.builtin.import_tasks: config-dns.yml

# - name: Setup autoconfig services
#   ansible.builtin.import_tasks: setup-autoconf.yml

- name: Setup roundcube services
  ansible.builtin.import_tasks: setup-roundcube.yml

##
##

- name: Ensure Email accounts folder correct permissions
  ansible.builtin.import_tasks: users-acc-ensure-permissions.yml
