---
- name: Create namespace
  kubernetes.core.k8s:
    template:
      - path: templates/ns.yml.j2

## REQUIRED TO BE INSTALLED FIRST, since generated secret by this certificate is done async
- name: Request certificate generation from Issuer with cert-manager's Certificate CRD
  kubernetes.core.k8s:
    template:
      - path: templates/certificate.yml.j2

# might be extensively long depending on Issuer
- name: Wait for the associated certificate's secret to be generated
  ansible.builtin.command: kubectl get secret {{ k8s__docker_mailserver__cert_secret_name }} -n {{ docker_mailserver__namespace }}
  register: secret_status
  changed_when: secret_status.rc != 0
  until: secret_status.rc == 0
  retries: 20
  delay: 20

- name: Then, Install Docker Mailserver
  kubernetes.core.k8s:
    template:
      - path: templates/mailserver/postfix-reject-config.yml.j2
      - path: templates/mailserver/pvc.yml.j2
      - path: templates/mailserver/config.yml.j2
      - path: templates/mailserver/ldap-secret.yml.j2
      - path: templates/mailserver/service.yml.j2
      - path: templates/mailserver/deploy.yml.j2
