---
- name: Roundcube Create Persistent Volume dir path
  ansible.builtin.file:
    path: "{{ iac__pv_path__roundcube }}"
    state: directory
    mode: "0755"

- name: Install Roundcube
  kubernetes.core.k8s:
    template:
      - path: templates/ns.yml.j2
      - path: templates/roundcube/config-ssl-staging.yml.j2
      - path: templates/roundcube/pv.yml.j2
      - path: templates/roundcube/config.yml.j2
      - path: templates/roundcube/service.yml.j2
      - path: templates/roundcube/deploy.yml.j2
      - path: templates/roundcube/ingress.yml.j2
