---
- name: Get users by id
  tags: [mail-acc-ensure-permissions]
  register: users
  vars:
    k8s__docker_mailserver_dc_query_string: "{{ root_domain | split('.') | map('regex_replace', '^(.*)$', 'dc=\\1') | list | join(',') }}"
    k8s__docker_mailserver_email_users_ldap_group_name: "Email Users"
  community.general.ldap_search:
    server_uri: ldap://{{ openldap_stack_ldap_server_hostname }}.{{ openldap_stack_namespace }}/
    bind_dn: cn=admin,{{ k8s__docker_mailserver_dc_query_string }}
    bind_pw: "{{ openldap_pwd }}"
    #
    dn: "cn={{ k8s__docker_mailserver_email_users_ldap_group_name }},{{ k8s__docker_mailserver_dc_query_string }}"
    scope: "onelevel"
    attrs:
      - uidNumber
      - homeDirectory

- name: Reaply legitimate permissions
  tags: [mail-acc-ensure-permissions]
  failed_when: false # replacement for ignore_errors
  ansible.builtin.command: |
    chown -R {{ item.uidNumber }}:{{
      k8s__docker_mailserver_mail_default_user_group
    }} {{ docker_mailserver_pv_path }}/data/{{ item.homeDirectory | split('/') | last }}
  loop: "{{ users.results }}"
