---
- name: Get users by id
  tags: [mail-acc-ensure-permissions]
  register: users
  community.general.ldap_search:
    server_uri: "{{ openldap_stack__ldap_uri }}"
    bind_dn: "{{ iac__ldap__admin__bind_dn }}"
    bind_pw: "{{ iac__ldap__admin__bind_pw }}"
    #
    dn: "{{ docker_mailserver__users_group_cn }}"
    filter: "(&(homeDirectory=*)(uidNumber=*))"
    scope: children
    attrs:
      - uidNumber
      - homeDirectory

# - name: Display
#   tags: [mail-acc-ensure-permissions]
#   ansible.builtin.debug:
#     var: users

- name: Re-apply legitimate permissions
  tags: [mail-acc-ensure-permissions]
  failed_when: false # replacement for ignore_errors
  loop: "{{ users.results }}"
  ansible.builtin.file:
    path: "{{ item.homeDirectory | regex_replace('^' + openldap_stack__users_home + '(.*)', iac__pv_path__docker_mailserver ~ '/data' + '\\1') }}"
    owner: "{{ item.uidNumber }}"
    group: "{{ docker_mailserver__users_group_id }}"
    recurse: true
    state: directory
  loop_control:
    label: "{{ item.homeDirectory | regex_replace('^' + openldap_stack__users_home + '(.*)', iac__pv_path__docker_mailserver ~ '/data' + '\\1') }}"
