---
- name: Get users by id
  tags: [mail-acc-ensure-permissions]
  register: users
  vars:
    openldap_stack__dc_query_string: "{{ root_domain | split('.') | map('regex_replace', '^(.*)$', 'dc=\\1') | list | join(',') }}"
    k8s__docker_mailserver_email_users_ldap_group_name: "Email Users"
  community.general.ldap_search:
    server_uri: "{{ openldap_stack__ldap_uri }}"
    bind_dn: "{{ openldap_stack__ldap_admin_cn }}"
    bind_pw: "{{ openldap_stack__ldap_admin_pwd }}"
    #
    dn: "cn={{ k8s__docker_mailserver_email_users_ldap_group_name }},{{ openldap_stack__dc_query_string }}"
    scope: "onelevel"
    attrs:
      - uidNumber
      - homeDirectory

- name: Re-apply legitimate permissions
  tags: [mail-acc-ensure-permissions]
  failed_when: false # replacement for ignore_errors
  loop: "{{ users.results }}"
  ansible.builtin.file:
    path: "{{ docker_mailserver_pv_path }}/data/{{ item.homeDirectory | split('/') | last }}"
    owner: "{{ item.uidNumber }}"
    group: "{{ k8s__docker_mailserver_mail_default_user_group }}"
    recurse: true
    state: directory
