---
- name: DKIM - Reboot mailserver
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "{{ docker_mailserver__server_hostname }}"
        namespace: "{{ docker_mailserver__namespace }}"
      spec:
        template:
          metadata:
            annotations:
              kubernetes.io/change-cause: "Restarted at {{ ansible_date_time.iso8601 }} because of DKIM"
              reloaded-at: "{{ ansible_date_time.iso8601 }}"
  when: (dkim_generation_cmd.stdout_lines | length) > 0
