---
- name: Add exception accessing unsafe HTTP private registry
  ansible.builtin.import_tasks: docker-unsafe.yml

- name: Finish configuring private registry (PersistentVolumes + password)
  ansible.builtin.import_tasks: config.more.yml

- name: Deploy registry UI
  ansible.builtin.import_tasks: ui.yml
