---
# allows to "sudo systemctl restart containerd" if needed
- name: Increase inotify user limit
  ansible.builtin.command: "sudo sysctl -w fs.inotify.max_user_instances=256"

- name: Install etcd (kubespray requisite)
  ansible.builtin.apt:
    name: etcd
    state: present # latest
    update_cache: true

- name: Run Pip w/ requisites (kubespray)
  ansible.builtin.pip:
    name:
      - jinja2
      - netaddr
      - jsonschema
      - kubernetes
