---
k8s__cert_manager__acme_email: "{{ cert_manager__acme_email | default(iac__postmaster_email) }}"
k8s__cert_manager__solve_with: "{{ cert_manager__solve_with | default('cloudflare_dns01') }}"
k8s__cert_manager__handle_trust_bundles: "{{ cert_manager__handle_trust_bundles | default(true) }}"
k8s__cert_manager__dns01__solver_secret: cloudflare-api-token-secret
k8s__cert_manager__dns01__solver_secret_key: api-token
k8s__cert_manager__default_ingress_classname: traefik
