---
- name: Install aptitude
  ansible.builtin.apt:
    name: aptitude
    state: present # latest
    update_cache: true

- name: Install passlib
  ansible.builtin.pip:
    name: passlib

- name: Install required system packages
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
      - python3-dev
      - libldap2-dev
      - libsasl2-dev
      - libssl-dev
    state: present # latest
    update_cache: true
