---
- name: Install k9s
  community.general.snap:
    name:
      - k9s

- name: Create symbolic link
  ansible.builtin.file:
    src: /snap/k9s/current/bin/k9s
    dest: /snap/bin/k9s
    state: link
