---
- name: Install passlib
  ansible.builtin.pip:
    name: passlib
    extra_args: --break-system-packages

- name: Install required system packages
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - virtualenv
      - python3-pip
      - python3-setuptools
      - python3-dev
      - libldap2-dev
      - libsasl2-dev
      - libssl-dev
      - jq
    state: present # latest
    update_cache: true
