---
- name: Install passlib
  community.general.pipx:
    state: inject
    name: ansible-dev-tools # name as used in pipx install (that installed ansible bin)
    inject_packages:
      - passlib

- name: Install required system packages
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - virtualenv
      - python3-pip
      - python3-setuptools
      - python3-dev
      - libldap2-dev
      - libsasl2-dev
      - libssl-dev
      - jq
    state: present # latest
    update_cache: true
