---
- name: Add stable chart repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

- name: Install cert-manager w/ Helm
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: "{{ cert_manager__namespace }}"
    create_namespace: true
    values:
      crds:
        enabled: true
      prometheus:
        enabled: false