---
- name: Add stable chart repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

- name: Install trust-manager w/ Helm
  kubernetes.core.helm:
    name: trust-manager
    chart_ref: jetstack/trust-manager
    release_namespace: cert-manager
    create_namespace: false
    values:
      secretTargets:
        enabled: true
        authorizedSecrets:
          - "{{ cert_manager__org_ca__cert_secret_name }}"

- name: Wait for pod to become ready
  ansible.builtin.command: |
    kubectl wait
    pods -l app.kubernetes.io/name=trust-manager
    --namespace=cert-manager
    --for=condition=Ready
    --timeout=120s
  register: pods_ready
  changed_when: pods_ready.rc != 0

- name: Install CA Bundles
  kubernetes.core.k8s:
    state: present
    template:
      - path: templates/ca-bundles/default.yml.j2
