---
- name: Add stable chart repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io
    force_update: true

- name: Install trust-manager w/ Helm
  kubernetes.core.helm:
    name: trust-manager
    chart_ref: jetstack/trust-manager
    release_namespace: "{{ cert_manager__namespace }}"
    create_namespace: false
    values:
      secretTargets:
        enabled: true
        authorizedSecrets:
          - "{{ cert_manager__org__root_ca__bundle }}"
