---
- name: Add stable chart repo
  kubernetes.core.helm_repository:
    name: kyverno-policy-reporter
    repo_url: https://kyverno.github.io/policy-reporter

- name: Install policy reporter w/ Helm
  kubernetes.core.helm:
    name: policy-reporter
    chart_ref: kyverno-policy-reporter/policy-reporter
    release_namespace: kyverno-policy-reporter
    create_namespace: true
    wait: true
    values:
      kyvernoPlugin:
        enabled: true
      ui:
        plugins:
          kyverno: true
        enabled: true
        ingress:
          enabled: true
          className: "{{  ingress_nginx_class }}"
          annotations:
            nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
            # when using Cloudflare's proxied DNS record
            nginx.ingress.kubernetes.io/ssl-redirect: "false"
            #
            ingress-dashboard/title: Kyverno Policy Reporter
            ingress-dashboard/description: Dashboard exposing Kyverno's activity
            ingress-dashboard/logo-url: /favicon.ico
            ingress-dashboard/assume-tls: "true"
            ingress-dashboard/hide: "false"
            #
            cloudflare-access/must-secure: "true"
          hosts:
            - host: policy-reporter.{{ root_domain }}
              paths:
                - path: /
                  pathType: ImplementationSpecific
