---
- name: Add stable chart repo
  kubernetes.core.helm_repository:
    name: helm-openldap
    repo_url: https://jp-gouin.github.io/helm-openldap/

- name: Create Persistent Volume dir path
  ansible.builtin.file:
    path: "{{ openldap_pv_path }}"
    state: directory
    mode: '0755'

- name: Create Persistent Volume
  kubernetes.core.k8s:
    state: present
    template:
      - path: templates/pv.yml.j2

- name: Install OpenLDAP Stack w/ Helm
  kubernetes.core.helm:
    name: "{{ openldap_stack_ldap_server_hostname }}"
    chart_ref: helm-openldap/openldap-stack-ha
    release_namespace: "{{ openldap_stack_namespace }}"
    create_namespace: true
    wait: true
    values:
      replicaCount: 1
      global:
        ldapDomain: "{{ root_domain }}"
        adminPassword: "{{ openldap_pwd }}"
        configPassword: "{{ openldap_pwd }}"
      replication:
        enabled: false
      persistence:
        enabled: true
        storageClass: "{{ local_storage_class_name }}"
        size: "8Gi"
      phpldapadmin:
        enabled: true
        # service:
        #   type: LoadBalancer
        env:
          PHPLDAPADMIN_LDAP_CLIENT_TLS_REQCERT: "never"
        ingress:
          enabled: true
          ingressClassName: "{{ ingress_nginx_class }}"
          ## Ingress Host
          hosts:
            - admin-ldap.{{ root_domain }}
          annotations:
            # when using Cloudflare's proxied DNS record
            nginx.ingress.kubernetes.io/ssl-redirect: "false"
            cert-manager.io/cluster-issuer: "{{ org_ca_name }}"
            nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
            #
            ingress-dashboard/title: OpenLDAP
            ingress-dashboard/description: Manage peoples directory of {{ root_domain }} organization (mails)
            ingress-dashboard/logo-url: /favicon.ico
            ingress-dashboard/assume-tls: "true"
            ingress-dashboard/hide: "false"
            #
            cloudflare-access/must-secure: "true"
      ltb-passwd:
        enabled: true
        # service:
        #   type: LoadBalancer
        ingress:
          enabled: true
          ingressClassName: "{{ ingress_nginx_class }}"
          hosts:
            - pwd-ldap.{{ root_domain }}
          annotations:
            # when using Cloudflare's proxied DNS record
            nginx.ingress.kubernetes.io/ssl-redirect: "false"
            cert-manager.io/cluster-issuer: "{{ org_ca_name }}"
            nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
            #
            ingress-dashboard/title: Mail Password changer
            ingress-dashboard/description: Allows to update your mail account password
            ingress-dashboard/logo-url: /favicon.ico
            ingress-dashboard/assume-tls: "true"
            ingress-dashboard/hide: "false"
            #
            cloudflare-access/must-secure: "false"
