---
- name: Add stable chart repo
  kubernetes.core.helm_repository:
    name: metallb
    repo_url: https://metallb.github.io/metallb

- name: Install MetalLB w/ Helm
  kubernetes.core.helm:
    name: metallb
    chart_ref: metallb/metallb
    release_namespace: "{{ base__k3s__metallb_namespace }}"
    create_namespace: true
    wait: true

# https://blog.mossroy.fr/2024/04/16/passage-sur-metallb-au-lieu-de-servicelb-sur-un-cluster-k3s/
- name: Configure default Layer 2 pool
  kubernetes.core.k8s:
    template:
      - path: templates/metallb/ippool.yml.j2
      - path: templates/metallb/l2ad.yml.j2

# https://blog.mossroy.fr/2024/04/16/passage-sur-metallb-au-lieu-de-servicelb-sur-un-cluster-k3s/
- name: Tweak Traefik for it to work with MetalLB
  kubernetes.core.k8s:
    template:
      - path: templates/metallb/hcc.traefik-tweaks.yml.j2
