---
- name: Wait until Traefik pod is created (and Ready !)
  until: >
    traefik_pod.resources is defined and
    traefik_pod.resources | length > 0 and
    traefik_pod.resources[0].status.phase == "Running"
  retries: 30
  delay: 2
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: "{{ base__k3s__default_namespace }}"
    label_selectors:
      - app.kubernetes.io/name=traefik
  register: traefik_pod

- name: Add Cloudflare's Full (Strict) SSL/TLS termination
  kubernetes.core.k8s:
    template:
      - path: templates/traefik/origin-ca.yml.j2
      - path: templates/traefik/tlsstore.yml.j2

###

- name: Process new Traefik configuration
  kubernetes.core.k8s:
    template:
      - path: templates/traefik/hcc.yml.j2

- name: Wait for Traefik pod to become ready again (would have ack new configuration then)
  register: pods_ready
  changed_when: pods_ready.rc != 0
  ansible.builtin.command: |
    kubectl wait pod -l app.kubernetes.io/name=traefik --namespace={{ base__k3s__default_namespace }} --for=condition=Ready --timeout=60s

###

- name: Expose Traefik dashboard
  kubernetes.core.k8s:
    template:
      - path: templates/traefik/dashboard.service.yml.j2
      - path: templates/traefik/dashboard.ingress.yml.j2
