---
- name: Get Token Path
  tags: [terraform]
  ansible.builtin.set_fact:
    argocd_syncer_token_path: "{{ generated_creds_dir }}/argocd-token.{{ argocd_account_for_github_syncer }}.txt"

- name: Add secrets and variables to specific Github organization repositories through their topic
  tags: [terraform]
  community.general.terraform:
    project_path: "{{ terraform_project_path }}/github-actions-repository-configure"
    state: present
    force_init: true
    complex_vars: true
    variables:
      github_organization: "{{ github_org }}"
      github_token: "{{ ansible_github_var_secrets_pat }}"
      #
      config:
        repository_socket: "{{ registry_host }}"
        repository_user: "{{ registry_default_push_user }}"
        cache_path: "{{ buildkit_local_mount_path }}"
      #
      variables:
        buildkit_remote_socket: "{{ buildkit_remote_socket }}"
      #
      secrets:
        argocd_syncer_token: "{{ lookup('ansible.builtin.file', argocd_syncer_token_path) }}"
