---
- name: Add stable chart repo
  kubernetes.core.helm_repository:
    name: vmware-tanzu
    repo_url: https://vmware-tanzu.github.io/helm-charts
    force_update: true

- name: Install Velero w/ Helm
  kubernetes.core.helm:
    name: velero
    chart_ref: vmware-tanzu/velero
    release_namespace: velero
    create_namespace: true
    values:
      initContainers:
        - name: velero-plugin-for-aws
          image: velero/velero-plugin-for-aws:latest
          volumeMounts:
            - mountPath: /target
              name: plugins
      credentials:
        name: velero-secret
        useSecret: true
        # Data to be stored in the Velero secret, if `useSecret` is true and `existingSecret` is empty.
        # As of the current Velero release, Velero only uses one secret key/value at a time.
        # The key must be named `cloud`, and the value corresponds to the entire content of your IAM credentials file.
        # Note that the format will be different for different providers, please check their documentation.
        # Here is a list of documentation for plugins maintained by the Velero team:
        # [AWS] https://github.com/vmware-tanzu/velero-plugin-for-aws/blob/main/README.md
        # [GCP] https://github.com/vmware-tanzu/velero-plugin-for-gcp/blob/main/README.md
        # [Azure] https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/blob/main/README.md
        secretContents:
          cloud: |
            [default]
            aws_access_key_id={{ minio__tenant__username }}
            aws_secret_access_key={{ minio__tenant_password }}
      configuration:
        # Parameters for the BackupStorageLocation(s). Configure multiple by adding other element(s) to the backupStorageLocation slice.
        # See https://velero.io/docs/v1.6/api-types/backupstoragelocation/
        backupStorageLocation:
          - name: # default
            # provider is the name for the backup storage location provider.
            provider: aws
            # bucket is the name of the bucket to store backups in. Required.
            bucket: "{{ minio__tenant__backup_storage__bucket_name }}"
            # Additional provider-specific configuration. See link above
            # for details of required/optional fields for your provider.
            config:
              region: "{{ minio__tenant__backup_storage__bucket_region }}"
              s3ForcePathStyle: "true"
              insecureSkipTLSVerify: true
              s3Url: "{{ minio__tenant__s3_url }}"
              publicUrl: "{{ minio__tenant__s3_url }}"

        # Parameters for the VolumeSnapshotLocation(s). Configure multiple by adding other element(s) to the volumeSnapshotLocation slice.
        # See https://velero.io/docs/v1.6/api-types/volumesnapshotlocation/
        volumeSnapshotLocation:
          - name: # default
            # provider is the name for the volume snapshot provider.
            provider: aws
            # Additional provider-specific configuration. See link above
            # for details of required/optional fields for your provider.
            config:
              region: "{{ minio__tenant__backup_storage__bucket_region }}"
              s3ForcePathStyle: "true"
              insecureSkipTLSVerify: true
              s3Url: "{{ minio__tenant__s3_url }}"
              publicUrl: "{{ minio__tenant__s3_url }}"
