---
# ensure services roles are installed and configured AFTER kubernetes is set
- name: Install Services w/in Kubernetes
  hosts: node1
  become: true
  roles:
    ##################
    ### INFRA CRDs ###
    ##################
    - role: k8s__cf_zto                 # Allow autoconfig of CF zero trust on services
    - role: k8s__cert_manager           # Finish cert-manager configuration (installed along kubespray)
    - role: k8s__external_dns           # Bind ingresses to DNS rules on Cloudflare
    - role: k8s__kyverno                # Policies enforcement and metadata injection
    #############################
    ### MANAGEMENT & INSIGHTS ###
    #############################
    - role: k8s__dashboard              # Setup dashboard (NOT installed from kubespray since it is outdated)
    # - role: k8s__skooner              # Alternative dashboard for k8s
    - role: k8s__ingress_dashboard      # List all ingresses available externally  
    # - role: k8s__prometheus_stack     # OPTIONAL, tracks insights from apps
    # - role: k8s__webmin               # OPTIONAL, allow control of a node / server
    # - role: k8s__portainer_ce         # OPTIONAL, allow control of docker / k8s instances
    ########################
    ### Safety & Backups ###
    ########################
    # - role: k8s__minio                # OPTIONAL, Storage Object service for storing backups and snapshots
    # - role: k8s__velero               # OPTIONAL, tool to orchestrate backups
    ####################
    ### Org Services ###
    ####################
    - role: k8s__openldap               # LDAP user & groups management
    - role: k8s__docker_mailserver      # Mail server
    ##############
    ### DevOps ###
    ##############
    - role: k8s__harbor                 # Docker images private registry
    # - role: k8s__github_arc           # OPTIONAL, allow github actions local runners
    # - role: k8s__hc_vault             # OPTIONAL, allow secure storage of private keys
    # - role: k8s__sentry               # OPTIONAL, receive debug reports (careful, high resources usage !)
    # - role: k8s__matomo               # OPTIONAL, allow usage tracking of apps / websites
    - role: k8s__argo_cd                # Automatize Continuous Delivery
    ############
    ### Apps ###
    ############
    # - role: k8s__odoo_community       # All-in-one, with alot of free apps (CRM and such)
    # - role: k8s__listmonk             # Allow marketing campaigns
    # - role: k8s__ez_appointments      # Allow clients to secure appointments
