---
- name: Enforce k8s namespace deletion
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Delete namespace finalizers
      # use "ansible.builtin.shell" for pipeable commands
      ansible.builtin.shell: |
        set -o pipefail
        export NS={{ ns }} && \
        kubectl get namespace "$NS" -o json | \
        tr -d "\n" | \
        sed 's/"finalizers": \[[^]]*\]/"finalizers": []/' | \
        kubectl replace --raw /api/v1/namespaces/$NS/finalize -f -
      args:
        executable: /bin/bash
      register: delete_namespace_finalizers
      changed_when: delete_namespace_finalizers.rc != 0
      failed_when: false # replacement for ignore_errors

    - name: Delete namespace
      ansible.builtin.command: |
        kubectl delete namespace {{ ns }}
      when: delete_namespace_finalizers.rc == 0
      register: delete_namespace
      changed_when: delete_namespace.rc != 0
      failed_when: false # replacement for ignore_errors

    - name: Ensure namespace is deleted
      ansible.builtin.command: |
        kubectl get namespace {{ ns }}
      register: check_namespace
      changed_when: check_namespace.rc != 0
      failed_when: false # replacement for ignore_errors
      retries: 5
      delay: 10
      until: check_namespace.rc != 0

    - name: Report namespace deletion status
      ansible.builtin.debug:
        msg: "Namespace {{ ns }} deleted successfully."
      when: check_namespace.rc != 0
