---
- name: Uninstall k3s
  hosts: all
  become: true
  vars:
    path_root: "{{ '/' if ansible_user == 'root' else '/home/' }}"
  tasks:
    - name: Delete .kube
      ansible.builtin.file:
        path: "{{ path_root }}{{ ansible_user }}/.kube/"
        state: absent
    - name: Uninstall k3s
      ansible.builtin.command: "/usr/local/bin/k3s-uninstall.sh"
