---
- name: Install K8s w/ kubespray
  hosts: all
  become: true
  tasks:
    - name: Include another playbook
      ansible.builtin.include_tasks: site.kubespray.yml

- name: Install Services
  hosts: all
  become: true
  tasks:
    - name: Include another playbook
      ansible.builtin.include_tasks: site.services.yml
