---
- name: Transfer scripts to container
  community.docker.docker_container_copy_into:
    container: "{{ sidekick__posthog__web_container }}"
    content: "{{ lookup('ansible.builtin.template', item) }}"
    container_path: /tmp/{{ item | basename | splitext | first }}
    owner_id: 0 # root
    group_id: 0 # root
    mode: "0755" # readable and executable by all users, writable by root
  loop:
    - templates/create_superuser.py.j2
    - templates/configure_mail.py.j2

#
- name: Execute Python scripts
  community.docker.docker_container_exec:
    container: "{{ sidekick__posthog__web_container }}"
    command: sh -c 'python manage.py shell < {{ item }}'
  loop:
    - /tmp/create_superuser.py
    - /tmp/configure_mail.py
