---
- name: Clone posthog GH repo to tag
  ansible.builtin.git:
    repo: "{{ sidekick__posthog__github_repo }}"
    dest: "{{ sidekick__posthog__install_dir }}"
    version: master
    single_branch: true
    depth: 1
    force: true

- name: Copy compose directory to installation directory (and make them executable)
  ansible.builtin.copy:
    src: "compose"
    dest: "{{ sidekick__posthog__install_dir }}"
    mode: "0755"
    owner: "{{ ansible_user | default('root') }}"
    group: "{{ ansible_user | default('root') }}"

##
##
##

- name: Rename docker-compose.hobby.yml to docker-compose.yml
  ansible.builtin.copy:
    src: "{{ sidekick__posthog__install_dir }}/docker-compose.hobby.yml"
    dest: "{{ sidekick__posthog__install_dir }}/docker-compose.yml"
    mode: "0644"
    owner: "{{ ansible_user | default('root') }}"
    group: "{{ ansible_user | default('root') }}"
    remote_src: true

- name: Rename docker-compose.base.yml to docker-compose.base-iac.yml
  ansible.builtin.copy:
    src: "{{ sidekick__posthog__install_dir }}/docker-compose.base.yml"
    dest: "{{ sidekick__posthog__install_dir }}/docker-compose.base-iac.yml"
    mode: "0644"
    owner: "{{ ansible_user | default('root') }}"
    group: "{{ ansible_user | default('root') }}"
    remote_src: true

##
## UPDATE docker-compose.yml
##

- name: Add traefik network to compose script
  ansible.builtin.command:
    argv:
      - yq
      - -i
      - .networks."{{ sidekick__posthog__traefik_network }}".external = true
      - "{{ sidekick__posthog__install_dir }}/docker-compose.yml"
  register: yq_network_result
  changed_when: yq_network_result.rc == 0

- name: Replace references to docker-compose.base.yml
  ansible.builtin.replace:
    path: "{{ sidekick__posthog__install_dir }}/docker-compose.yml"
    regexp: "{{ item.regex }}"
    replace: "{{ item.replace }}"
  register: replace_result
  changed_when: replace_result.changed
  loop:
    - regex: '\./posthog/'
      replace: "./"
    - regex: 'docker-compose\.base\.yml'
      replace: docker-compose.base-iac.yml

- name: Remove caddy from docker-compose.yml
  ansible.builtin.command:
    argv:
      - yq
      - -i
      - del(.services.caddy, .volumes."caddy-config", .volumes."caddy-data")
      - "{{ sidekick__posthog__install_dir }}/docker-compose.yml"
  register: yq_result
  changed_when: yq_result.rc == 0

- name: Add traefik labels
  block:
    - name: Add traefik labels to "web"
      ansible.builtin.command:
        argv:
          - yq
          - -i
          - .services.web.labels += ["{{ item }}"]
          - "{{ sidekick__posthog__install_dir }}/docker-compose.yml"
      register: yq_result_labels_web
      changed_when: yq_result_labels_web.rc == 0
      loop: "{{ sidekick__posthog__traefik_exposed__web }}"
    - name: Add traefik labels to "livestream"
      ansible.builtin.command:
        argv:
          - yq
          - -i
          - .services.livestream.labels += ["{{ item }}"]
          - "{{ sidekick__posthog__install_dir }}/docker-compose.yml"
      register: yq_result_labels_livestream
      changed_when: yq_result_labels_livestream.rc == 0
      loop: "{{ sidekick__posthog__traefik_exposed__livestream }}"

##
##

- name: Link exposed services to traefik
  ansible.builtin.command:
    argv:
      - yq
      - -i
      - .services."{{ item }}".networks += ["{{ sidekick__posthog__traefik_network }}"]
      - "{{ sidekick__posthog__install_dir }}/docker-compose.yml"
  register: yq_result_networks
  changed_when: yq_result_networks.rc == 0
  loop:
    - web
    - livestream

- name: Link all other services between each other
  ansible.builtin.command:
    argv:
      - yq
      - -i
      - .services.*.networks += ["default"]
      - "{{ sidekick__posthog__install_dir }}/docker-compose.yml"
  register: yq_result_networks
  changed_when: yq_result_networks.rc == 0

##
## UPDATE docker-compose.base-iac.yml
##

- name: Add additional environment variables to worker
  ansible.builtin.command:
    argv:
      - yq
      - -i
      - '.services.worker.environment."{{ item.key }}" = "{{ item.value }}"'
      - "{{ sidekick__posthog__install_dir }}/docker-compose.base-iac.yml"
  register: yq_result_env
  changed_when: yq_result_env.rc == 0
  loop: "{{ sidekick__posthog__more_env_vars | dict2items }}"

##
##
##

- name: Check if .env file exists
  ansible.builtin.stat:
    path: "{{ sidekick__posthog__install_dir }}/.env"
  register: env_file

- name: Create .env file from template
  ansible.builtin.template:
    src: .env.j2
    dest: "{{ sidekick__posthog__install_dir }}/.env"
    mode: "0644"
    owner: "{{ ansible_user | default('root') }}"
    group: "{{ ansible_user | default('root') }}"
  when: not env_file.stat.exists

##
## Install GeoLite2 database for IP geolocation
##

- name: Ensure shared directory exists
  ansible.builtin.file:
    path: "{{ sidekick__posthog__install_dir }}/shared"
    state: directory
    mode: "0755"
    owner: "{{ ansible_user | default('root') }}"
    group: "{{ ansible_user | default('root') }}"

- name: Download GeoLite2-City.mmdb from GitHub
  ansible.builtin.get_url:
    url: "https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-City.mmdb"
    dest: "{{ sidekick__posthog__install_dir }}/shared/GeoLite2-City.mmdb"
    mode: "0644"
    owner: "{{ ansible_user | default('root') }}"
    group: "{{ ansible_user | default('root') }}"
    force: false
