---
- name: Create directory for PostHog installation
  ansible.builtin.file:
    path: "{{ sidekick__posthog__install_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ ansible_user | default('root') }}"
    group: "{{ ansible_user | default('root') }}"

# Téléchargement du script de déploiement PostHog
- name: Download PostHog deployment script
  ansible.builtin.get_url:
    url: "{{ sidekick__posthog__deploy_script_url }}"
    dest: "{{ sidekick__posthog__deploy_script_dest }}"
    mode: "0755"
    force: true
    validate_certs: true

# https://posthog.com/docs/self-host#setting-up-the-stack
- name: Run PostHog hobby deployment script
  ansible.builtin.command:
    cmd: /bin/bash {{ sidekick__posthog__deploy_script_dest }}
    chdir: "{{ sidekick__posthog__install_dir }}"
  environment:
    # https://posthog.com/docs/self-host/configure/environment-variables
    SITE_URL: "{{ sidekick__posthog__site_url }}"
    SECRET_KEY: "{{ posthog_secret_key }}"
    ##
    IS_BEHIND_PROXY: "1"
    # TRUSTED_PROXIES: "<IPs>"
    TRUST_ALL_PROXIES: "1"
    #
    EMAIL_ENABLED: "1"
    EMAIL_HOST: "{{ docker_mailserver__external_hostname }}"
    EMAIL_PORT: "587"
    EMAIL_DEFAULT_FROM: "{{ iac__donotreply_email }}"
    EMAIL_HOST_USER: "{{ iac__donotreply_username }}"
    EMAIL_HOST_PASSWORD: "{{ iac__donotreply_password }}"
    EMAIL_USE_TLS: "1"
    EMAIL_USE_SSL: "0"
