---
- name: Create directory for PostHog installation
  ansible.builtin.file:
    path: "{{ sidekick__posthog__install_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ ansible_user | default('root') }}"
    group: "{{ ansible_user | default('root') }}"

- name: Download PostHog files from GitHub
  ansible.builtin.get_url:
    url: "{{ sidekick__posthog__github_head }}/{{ item }}"
    dest: "{{ sidekick__posthog__install_dir }}/{{ item }}"
    mode: "0644"
    owner: "{{ ansible_user | default('root') }}"
    group: "{{ ansible_user | default('root') }}"
  with_items: "{{ sidekick__posthog__github_files_to_dl }}"

- name: Rename modified docker-compose.hobby.yml to docker-compose.yml
  ansible.builtin.copy:
    src: "{{ sidekick__posthog__install_dir }}/docker-compose.hobby.yml"
    dest: "{{ sidekick__posthog__install_dir }}/docker-compose.yml"
    mode: "0644"
    owner: "{{ ansible_user | default('root') }}"
    group: "{{ ansible_user | default('root') }}"
    remote_src: true

- name: Remove caddy from docker-compose.yml using yq (inplace mandatory)
  ansible.builtin.command:
    argv:
      - yq
      - -y
      - -i
      - del(.services.caddy, .volumes."caddy-config", .volumes."caddy-data")
      - "{{ sidekick__posthog__install_dir }}/docker-compose.yml"
  register: yq_result
  changed_when: yq_result.rc == 0

- name: Check if .env file exists
  ansible.builtin.stat:
    path: "{{ sidekick__posthog__install_dir }}/.env"
  register: env_file

- name: Create .env file from template
  ansible.builtin.template:
    src: .env.j2
    dest: "{{ sidekick__posthog__install_dir }}/.env"
    mode: "0644"
    owner: "{{ ansible_user | default('root') }}"
    group: "{{ ansible_user | default('root') }}"
  when: not env_file.stat.exists
##
##
##

# environment:
#   # https://posthog.com/docs/self-host/configure/environment-variables
#   SITE_URL: "{{ sidekick__posthog__site_url }}"
#   SECRET_KEY: "{{ posthog_secret_key }}"
#   ##
#   IS_BEHIND_PROXY: "1"
#   # TRUSTED_PROXIES: "<IPs>"
#   TRUST_ALL_PROXIES: "1"
#   #
#   EMAIL_ENABLED: "1"
#   EMAIL_HOST: "{{ docker_mailserver__external_hostname }}"
#   EMAIL_PORT: "587"
#   EMAIL_DEFAULT_FROM: "{{ iac__donotreply_email }}"
#   EMAIL_HOST_USER: "{{ iac__donotreply_username }}"
#   EMAIL_HOST_PASSWORD: "{{ iac__donotreply_password }}"
#   EMAIL_USE_TLS: "1"
#   EMAIL_USE_SSL: "0"
