---
k8s__harbor__storage_capacity: 40Gi

k8s__harbor__cert_name: harbor
k8s__harbor__cert_secret_name: "{{ k8s__harbor__cert_name }}-certs"

k8s__harbor__internal_hostname__api: "{{ harbor__internal_hostname__registry_v2 }}" # same as registry (see ingress)

k8s__harbor__internal_tls_secret_name: harbor-internal-tls
