---
- name: Install LDAP for Python (1/2)
  ansible.builtin.apt:
    pkg:
      - python3-ldap
    state: present # latest
    update_cache: true

- name: Install LDAP for Python (2/2)
  ansible.builtin.pip:
    extra_args: --break-system-packages
    name:
      - python-ldap
      - passlib

- name: Wait for OpenLDAP pod to become ready
  register: pods_ready
  changed_when: pods_ready.rc != 0
  ansible.builtin.command: |
    kubectl wait pod/openldap-0 --namespace=openldap-stack --for=condition=Ready --timeout=240s

# Ensure User group matching Docker usergroup exists to allow auto-creation of LDAP user mail directories
- name: Create default user group for email users
  community.general.ldap_entry:
    server_uri: "{{ openldap_stack__ldap_uri }}"
    bind_dn: "{{ openldap_stack__ldap_admin_cn }}"
    bind_pw: "{{ openldap_stack__ldap_admin_pwd }}"
    #
    dn: cn={{ docker_mailserver__users_group_name }},{{ openldap_stack__dc_query_string }}
    objectClass:
      - top
      - posixGroup
    attributes:
      gidnumber: "{{ docker_mailserver__users_group_id }}"
      description: "{{ docker_mailserver__users_group_description }}"

#
- name: Create default accounts
  community.general.ldap_entry:
    server_uri: "{{ openldap_stack__ldap_uri }}"
    bind_dn: "{{ openldap_stack__ldap_admin_cn }}"
    bind_pw: "{{ openldap_stack__ldap_admin_pwd }}"
    #
    dn: cn={{ item.username }},cn={{ docker_mailserver__users_group_name }},{{ openldap_stack__dc_query_string }}
    objectClass:
      - top
      - posixAccount
      - inetOrgPerson
    attributes:
      gidnumber: "{{ docker_mailserver__users_group_id }}"
      homedirectory: /home/users/{{ item.username }}
      mail:
        # - "{{ item.username }}"
        - "{{ item.email }}"
      sn: "{{ item.username }}"
      uid: "{{ item.username }}"
      uidnumber: "{{ item.uidn }}"
      userpassword: "{CRYPT}{{ item.password | password_hash('md5') }}"
  loop:
    - username: "{{ iac__postmaster_username }}"
      password: "{{ iac__postmaster_password }}"
      email: "{{ iac__postmaster_email }}"
      uidn: 1000
    - username: "{{ iac__donotreply_username }}"
      password: "{{ iac__donotreply_password }}"
      email: "{{ iac__donotreply_email }}"
      uidn: 10000
  loop_control:
    label: "{{ item.email }}"
