---
- name: Add stable chart repo
  kubernetes.core.helm_repository:
    name: helm-openldap
    repo_url: https://jp-gouin.github.io/helm-openldap/

- name: Create Persistent Volume dir path
  ansible.builtin.file:
    path: "{{ openldap_pv_path }}"
    state: directory
    mode: "0755"

- name: Create Persistent Volume
  kubernetes.core.k8s:
    state: present
    template:
      - path: templates/openldap/pv.yml.j2

- name: Install OpenLDAP Stack w/ Helm
  kubernetes.core.helm:
    name: "{{ openldap_stack__ldap_server_hostname }}"
    chart_ref: helm-openldap/openldap-stack-ha
    release_namespace: "{{ openldap_stack__namespace }}"
    create_namespace: true
    wait: true
    values:
      replicaCount: 1
      global:
        ldapDomain: "{{ root_domain }}"
        adminPassword: "{{ openldap_stack__ldap_admin_pwd }}"
        configPassword: "{{ openldap_stack__ldap_admin_pwd }}"
      replication:
        enabled: false
      persistence:
        enabled: true
        storageClass: "{{ local_storage_class_name }}"
        size: "8Gi"
      phpldapadmin:
        enabled: false
      ltb-passwd:
        enabled: false
