---
- name: Create Persistent Volume dir path
  ansible.builtin.file:
    path: "{{ portainer_pv_path }}"
    state: directory
    mode: "0755"

- name: Define or create Persistent volume
  kubernetes.core.k8s:
    state: present
    template:
      - path: "templates/pv.yml.j2"

- name: Add stable chart repo Portainer CE
  kubernetes.core.helm_repository:
    name: portainer
    repo_url: "https://portainer.github.io/k8s/"

- name: Install Portainer CE w/ Helm
  kubernetes.core.helm:
    name: portainer
    chart_ref: "portainer/portainer"
    release_namespace: portainer
    create_namespace: true
    values:
      nodeSelector:
        kubernetes.io/hostname: "{{ master_node_name }}"
      service:
        type: "LoadBalancer" # https://docs.tigera.io/archive/v3.18/networking/advertise-service-ips#before-you-begin
      tls:
        force: true
        # existingSecret: "portainer-ce-certs"
      ingress:
        enabled: true
        ingressClassName: "{{ ingress_nginx_class }}"
        annotations:
          kubernetes.io/ingress.class: "{{ ingress_nginx_class }}"
          # when using Cloudflare's proxied DNS record
          nginx.ingress.kubernetes.io/ssl-redirect: "false"
          cert-manager.io/cluster-issuer: "selfsigned" # "{{ cluster_issuer_name }}"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        hosts:
          - host: "{{ portainer_host }}"
            paths:
              - path: "/"
        tls:
          - hosts:
              #   - "*.{{ root_domain }}"
              # secretName: nw-wildcard-certs
              - "{{ portainer_host }}"
            secretName: "portainer-ce-certs"
  vars:
    portainer_host: "portainer.{{ root_domain }}"
