---
- name: Create Persistent Volume dir path
  ansible.builtin.file:
    path: "{{ portainer_pv_path }}"
    state: directory
    mode: "0755"

- name: Define or create Persistent volume
  kubernetes.core.k8s:
    state: present
    template:
      - path: templates/ns.yml.j2
      - path: templates/pv.yml.j2
      - path: templates/secret.yml.j2

- name: Add stable chart repo Portainer CE
  kubernetes.core.helm_repository:
    name: portainer
    repo_url: https://portainer.github.io/k8s/

- name: Install Portainer CE w/ Helm
  vars:
    portainer_host: portainer.{{ root_domain }}
  kubernetes.core.helm:
    name: portainer
    chart_ref: portainer/portainer
    release_namespace: portainer
    create_namespace: false
    values:
      nodeSelector:
        kubernetes.io/hostname: "{{ master_node_name }}"
      persistence:
        storageClass: "{{ local_storage_class_name }}"
      service:
        type: LoadBalancer # https://docs.tigera.io/archive/v3.18/networking/advertise-service-ips#before-you-begin
      tls:
        force: true
        # existingSecret: "portainer-ce-certs"
      ingress:
        enabled: true
        ingressClassName: "{{ ingress_nginx_class }}"
        annotations:
          kubernetes.io/ingress.class: "{{ ingress_nginx_class }}"
          # when using Cloudflare's proxied DNS record
          nginx.ingress.kubernetes.io/ssl-redirect: "false"
          cert-manager.io/cluster-issuer: "{{ org_ca_name }}"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          #
          ingress-dashboard/title: Portainer
          ingress-dashboard/description: Alternative cluster management dashboard for Docker, Swarm of k8s
          ingress-dashboard/logo-url: /favicon.ico
          ingress-dashboard/assume-tls: "true"
          ingress-dashboard/hide: "false"
          #
          cloudflare-access/must-secure: "true"
        hosts:
          - host: "{{ portainer_host }}"
            paths:
              - path: /

- name: Wait for pod to become ready
  ansible.builtin.command: |
    kubectl wait
    pod -l app.kubernetes.io/name=portainer
    --namespace=portainer
    --for=condition=Ready
    --timeout=120s
  register: pods_ready
  changed_when: pods_ready.rc != 0

##
## Password auto-config
##

- name: Load facts
  ansible.builtin.set_fact:
    portainer_pod_args_replace:
      - op: replace
        path: /spec/template/spec/volumes
        value:
          - name: admin-pwd
            secret:
              secretName: portainer-admin
      - op: replace
        path: /spec/template/spec/containers/0/volumeMounts
        value:
          - name: admin-pwd
            mountPath: /run/secrets
      - op: replace
        path: /spec/template/spec/containers/0/args
        value:
          - --admin-password-file='/run/secrets/portainer-pass'

#
- name: Patch with admin password
  ansible.builtin.command: "kubectl patch deployment portainer -n portainer --type='json' -p='{{ portainer_pod_args_replace | to_json }}'"
