---
- name: Add stable chart repo
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Install Prometheus Stack w/ Helm
  kubernetes.core.helm:
    name: prometheus-stack
    chart_ref: prometheus-community/kube-prometheus-stack
    release_namespace: prometheus-stack
    create_namespace: true
    values:
      grafana:
        adminPassword: "{{ grafana_admin_pwd }}"
        service:
          type: LoadBalancer
        ingress:
          enabled: true
          ingressClassName: "{{ ingress_nginx_class }}"
          annotations:
            # Will be handled by Cloudflare proxy
            nginx.ingress.kubernetes.io/ssl-redirect: "false"
            cert-manager.io/cluster-issuer: "{{ org_ca_name }}"
            #
            ingress-dashboard/title: Graphana
            ingress-dashboard/description: Hub for custom dashboards and visualization
            ingress-dashboard/logo-url: /favicon.ico
            ingress-dashboard/assume-tls: "true"
            ingress-dashboard/hide: "true"
            #
            cloudflare-acccess/must-secure: "true"
          hosts:
            - graphana.{{ root_domain }}
      prometheus:
        service:
          type: LoadBalancer
        ingress:
          enabled: true
          ingressClassName: "{{ ingress_nginx_class }}"
          annotations:
            # Will be handled by Cloudflare proxy
            nginx.ingress.kubernetes.io/ssl-redirect: "false"
            cert-manager.io/cluster-issuer: "{{ org_ca_name }}"
            #
            ingress-dashboard/title: Prometheus
            ingress-dashboard/description: Tracks logs of k8s cluster resources
            ingress-dashboard/logo-url: /favicon.ico
            ingress-dashboard/assume-tls: "true"
            ingress-dashboard/hide: "false"
            #
            cloudflare-acccess/must-secure: "true"
          hosts:
            - prometheus.{{ root_domain }}
