---
- name: Add stable chart repo
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Install Prometheus Stack w/ Helm
  kubernetes.core.helm:
    name: prometheus-stack
    chart_ref: prometheus-community/kube-prometheus-stack
    release_namespace: prometheus-stack
    create_namespace: true
    values:
      grafana:
        adminPassword: "{{ grafana_admin_pwd }}"
        service:
          type: LoadBalancer
        ingress:
          enabled: true
          ingressClassName: "{{ ingress_nginx_class }}"
          annotations:
            # Will be handled by Cloudflare proxy
            nginx.ingress.kubernetes.io/ssl-redirect: "false"
            cert-manager.io/cluster-issuer: "selfsigned"
          hosts:
            - graphana.{{ root_domain }}
      prometheus:
        service:
          type: LoadBalancer
        ingress:
          enabled: true
          ingressClassName: "{{ ingress_nginx_class }}"
          annotations:
            # Will be handled by Cloudflare proxy
            nginx.ingress.kubernetes.io/ssl-redirect: "false"
            cert-manager.io/cluster-issuer: "selfsigned"
          hosts:
            - prometheus.{{ root_domain }}
