---
- name: Check Harbor API health
  ansible.builtin.uri:
    url: "{{ harbor__internal_hostname__registry_v2__url }}/api/v2.0/health"
    method: GET
    return_content: true
    status_code: 200
  register: result
  until: result.status == 200
  retries: 20
  delay: 5
  ignore_errors: true

- name: Create private Harbor project
  ansible.builtin.uri:
    url: "{{ harbor__internal_hostname__registry_v2__url }}/api/v2.0/projects"
    method: POST
    headers:
      Content-Type: application/json
      Accept: application/json
      Authorization: "Basic {{ (harbor__admin_username + ':' + harbor__admin_password) | b64encode }}"  # Replace with your credentials
    body_format: json
    body:
      project_name: "{{ iac__github_org | lower }}"
      metadata:
        public: "false"
    validate_certs: false
    status_code:
      - 201 # created
      - 409 # conflict, means it exists
