---
- name: Configure k3s containerd private repositories
  ansible.builtin.template:
    src: templates/registries.yaml.j2
    dest: /etc/rancher/k3s/registries.yaml

- name: Restart k3s to ack changes
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: k3s

##
##

- name: Check Harbor API health
  ansible.builtin.uri:
    url: "{{ harbor__internal_hostname__registry_v2__url }}/api/v2.0/health"
    method: GET
    headers:
      Content-Type: application/json
    return_content: true
    status_code: 200
    timeout: 1
  register: result
  until: result.status == 200
  retries: 20
  delay: 5
  ignore_errors: true

- name: Create private Harbor project
  ansible.builtin.uri:
    url: "{{ harbor__internal_hostname__registry_v2__url }}/api/v2.0/projects"
    method: POST
    headers:
      Content-Type: application/json
      Accept: application/json
      Authorization: "Basic {{ (harbor__admin_username + ':' + harbor__admin_password) | b64encode }}" # Replace with your credentials
    body_format: json
    body:
      project_name: "{{ harbor__org_project_name }}"
      metadata:
        public: "false"
    validate_certs: false
    status_code:
      - 201 # created
      - 409 # conflict, means it exists
