---
- name: Create private Harbor project
  ansible.builtin.uri:
    url: "http://{{ k8s__harbor__core__internal_hostname }}/api/v2.0/projects"
    method: POST
    headers:
      Content-Type: application/json
      Accept: application/json
      Authorization: "Basic {{ (k8s__harbor__admin_username + ':' + harbor__admin_password) | b64encode }}"  # Replace with your credentials
    body_format: json
    body:
      project_name: "{{ iac__github_org | lower }}"
      metadata:
        public: "false"
    validate_certs: true  # Set to yes if using valid certificates
    status_code:
      - 201 # created
      - 409 # conflict, means it exists
