---
# allows to "sudo systemctl restart containerd" if needed
- name: Increase inotify user limit
  ansible.posix.sysctl:
    name: fs.inotify.max_user_instances
    value: "256"
    sysctl_set: true

#
- name: Update apt and install kubernetes python wrapper
  ansible.builtin.apt:
    pkg:
      - python3-kubernetes
    state: present # latest
    update_cache: true

- name: Run Pip w/ requisites (kubespray)
  ansible.builtin.pip:
    extra_args: --break-system-packages
    name: 
      - jinja2
      - jsonschema
      # from https://github.com/kubernetes-sigs/kubespray/blob/master/requirements.txt
      - cryptography
      - jmespath
      - netaddr
