---
- name: Install postgres
  ansible.builtin.import_tasks: setup.postgres.yml

- name: Install Listmonk
  ansible.builtin.import_tasks: setup.listmonk.yml

- name: Configure Listmonk
  ansible.builtin.import_tasks: configure.listmonk.yml
