---
- name: Install listmonk
  kubernetes.core.k8s:
    template:
      - path: templates/ns.yml.j2
      - path: templates/app/pvc-uploads.yml.j2
      - path: templates/app/secret.yml.j2
      - path: templates/app/service.yml.j2
      - path: templates/app/deploy.yml.j2
      - path: templates/app/ingress.yml.j2
      - path: templates/app/config.yml.j2
