---
- name: Create Persistent Volume dir path
  ansible.builtin.file:
    path: "{{ item.path }}"
    # owner: "{{ item.owner }}"
    # group: "{{ item.group }}"
    state: directory
    mode: '0755'
  loop:
    - path: "{{ iac__pv_path__matomo__db }}"
      # owner: 1001
      # group: 1001
    - path: "{{ iac__pv_path__matomo__app }}"
      # owner: 1001
      # group: 0

- name: Prepare volumes manifests
  kubernetes.core.k8s:
    state: present
    template:
      - path: templates/ns.yml.j2
      - path: templates/app/pv.yml.j2
      - path: templates/db/pv.yml.j2
      - path: templates/db/pvc.yml.j2

- name: MariaDB Update
  register: mariadb_pwd
  ansible.builtin.command: |
    set -o pipefail
    kubectl get secret -n matomo matomo-mariadb -o jsonpath="{.data.mariadb-root-password}" | base64 -d
  failed_when: false # replacement for ignore_errors
  changed_when: mariadb_pwd.rc != 0

- name: Install Matomo Stack w/ Helm
  kubernetes.core.helm:
    name: matomo
    chart_ref: oci://registry-1.docker.io/bitnamicharts/matomo
    release_namespace: "{{ k8s__matomo_namespace }}"
    create_namespace: false
    values:
      volumePermissions:
        enabled: true
      podLabels:
        app: matomo
      persistence:
        storageClass: "{{ iac__local_storage__class_name }}"
        selector:
          matchLabels:
            name: matomo-app
      mariadb:
        auth:
          rootPassword: "{{ mariadb_pwd.stdout | default('') }}"
        primary:
          persistence:
            existingClaim: db
      # externalDatabase:
      #   host: "matomo-mariadb.matomo"
      matomoUsername: "{{ matomo__admin_username }}"
      matomoPassword: "{{ matomo__admin_password }}"
      matomoEmail: "{{ iac__postmaster_email }}"
      matomoWebsiteName: Matomo
      matomoWebsiteHost: https://{{ k8s__matomo__external_hostname }}
      #
      smtpAuth: Login
      smtpHost: docker-mailserver.docker-mailserver
      smtpPort: 587
      smtpUser: "{{ iac__donotreply_username }}"
      smtpPassword: "{{ iac__donotreply_password }}"
      smtpProtocol: tls
      noreplyName: "Do Not Reply"
      noreplyAddress: "{{ iac__donotreply_email }}"

      #
      service:
        type: LoadBalancer
        externalTrafficPolicy: Local
      ingress:
        enabled: true
        ingressClassName: "{{ iac__ingress_nginx_class }}"
        hostname: "{{ k8s__matomo__external_hostname }}"
        annotations:
          # when using Cloudflare's proxied DNS record
          nginx.ingress.kubernetes.io/ssl-redirect: "false"
          cert-manager.io/cluster-issuer: "{{ cert_manager__org_ca__name }}"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          #
          external-dns.alpha.kubernetes.io/hostname: "{{ k8s__matomo__external_hostname }}"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          #
          ingress-dashboard/title: Matomo
          ingress-dashboard/description: Tracks stats on our organization public websites
          ingress-dashboard/logo-url: /favicon.ico
          ingress-dashboard/assume-tls: "true"
          ingress-dashboard/hide: "false"

- name: Wait for pod to become ready
  ansible.builtin.command: |
    kubectl wait
    pod -l app=matomo
    --namespace=matomo
    --for=condition=Ready
    --timeout=240s
  register: pods_ready
  changed_when: pods_ready.rc != 0

- name: Wait until the config file exist
  ansible.builtin.wait_for:
    path: "{{ iac__pv_path__matomo__app }}/config/config.ini.php"

- name: Edit ini
  community.general.ini_file:
    path: "{{ iac__pv_path__matomo__app }}/config/config.ini.php"
    section: General
    no_extra_spaces: true
    option: assume_secure_protocol
    values: '1'
    mode: "0775"
