apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gha-cache
  namespace: "{{ k8s__github_arc__systems_ns }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ k8s__github_arc__local_cache_size }}"