apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "{{ k8s__github_arc_cache_storage_class_name }}"
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer