---
k8s__odoo_community__namespace: odoo-mosellane
k8s__odoo_community__external_hostname: odoo-mosellane.{{ iac__root_domain }}

# name of postgres's helm setup manifests
k8s__odoo_community__db__name: odoo-postgresql

#
k8s__odoo_community__db__config__admin_password: odoo-admin_PwD1231.L14d
# https://github.com/odoo/odoo/issues/182551
# https://hub.docker.com/_/odoo
# Default expected values by Odoo for initial database access
k8s__odoo_community__db__config__db_name: postgres
k8s__odoo_community__db__config__username: odoo
k8s__odoo_community__db__config__password: odoo
k8s__odoo_community__db__config__host: "{{ k8s__odoo_community__db__name }}.{{ k8s__odoo_community__namespace }}.{{ iac__svc_cluster_host }}"

# Name of the "database" that Odoo will create on its own; must be separate from previous db names
k8s__odoo_community__odoo_instance_db_name: odoo1
k8s__odoo_community__odoo_instance_data_dir: /var/lib/odoo
k8s__odoo_community__odoo_instance_addons_dir: /mnt/extra-addons

#
k8s__odoo_community__odoo_included_modules: ['contacts', 'stock', 'account', 'sale_management']

#
k8s__odoo_community__add_server_definitions_into_pgadmin: false
