---
k8s__odoo_community__custom_tld: "{{ odoo_community__custom_tld | default('odoo') }}"
k8s__odoo_community__auto_install: "{{ odoo_community__auto_install | default(true) }}"

# Name of the "database" that Odoo will create on its own
# @note: Since Odoo can automatically handle DB binding by scanning its Third Level Domain;
# even if the feature is not used and by convention, use TLD as initial database name.
k8s__odoo_community__odoo_instance__db_name: "{{ odoo_community__auto_install | ternary(k8s__odoo_community__custom_tld, 'False') }}"

#
k8s__odoo_community__namespace: odoo-community
k8s__odoo_community__external_hostname: "{{ k8s__odoo_community__custom_tld }}.{{ iac__root_domain }}"
k8s__odoo_community__metadata_name: odoo
k8s__odoo_community__app_selector_name: odoo

#
k8s__odoo_community__external_hostname_acme: "{{ odoo_community__external_hostname_acme | default('') }}"

# name of postgres's helm setup manifests
k8s__odoo_community__db__name: odoo-postgresql

#
k8s__odoo_community__odoo_docker_image: ghcr.io/qalisa/odoo:18-0

#
k8s__odoo_community__db__config__admin_password: odoo-admin_PwD1231.L14d
# https://github.com/odoo/odoo/issues/182551
# https://hub.docker.com/_/odoo
# Default expected values by Odoo for initial database access
k8s__odoo_community__db__config__db_name: postgres
k8s__odoo_community__db__config__username: odoo
k8s__odoo_community__db__config__password: odoo
k8s__odoo_community__db__config__host: "{{ k8s__odoo_community__db__name }}.{{ k8s__odoo_community__namespace }}.{{ iac__svc_cluster_host }}"

k8s__odoo_community__odoo_instance__jsonrpc: >-
  http://{{ k8s__odoo_community__metadata_name }}.{{ k8s__odoo_community__namespace }}.{{ iac__svc_cluster_host }}/jsonrpc

# these are the default expected by a fresh install of Odoo; these ought to be replaced
k8s__odoo_community__odoo_instance__default__admin_username: admin
k8s__odoo_community__odoo_instance__default__admin_password: admin
k8s__odoo_community__odoo_instance__default__company_name: My Company

#
k8s__odoo_community__odoo_instance__wanted_locale: "{{ iac__prefered_lang__country }}"
k8s__odoo_community__odoo_instance__wanted_currency: EUR
k8s__odoo_community__odoo_instance__wanted_coa: France

#
k8s__odoo_community__odoo_instance__admin_username: "{{ iac__postmaster_email }}"
k8s__odoo_community__odoo_instance__admin_password: "{{ iac__postmaster_password }}"

k8s__odoo_community__odoo_instance__data_dir: /var/lib/odoo
k8s__odoo_community__odoo_instance__addons_dir: /mnt/extra-addons

k8s__odoo_community__odoo_included_modules:
  ["l10n_{{ iac__prefered_lang__sub }}_account", "contacts", "sale_management"]

#
k8s__odoo_community__add_server_definitions_into_pgadmin: false
k8s__odoo_community__use_local_backup_pvc: true

##
##
##

#
k8s__odoo_community__addons:
  qalisa:
    branch: "18-0"
    url: https://github.com/Qalisa/odoo-apps
    repoSubpath: /addons
  odoomates:
    branch: "18.0"
    url: https://github.com/Qalisa/odooapps # *customized by Qalisa (mostly translated)*
    repoSubpath: ""
  eqp:
    branch: "18.0"
    url: https://github.com/Qalisa/eqp_odoo_addons # *customized by Qalisa (mostly translated)*
    repoSubpath: ""

#
k8s__odoo_community__odoo_instance__addons_paths_: >-
  {% for addon_name, addon in k8s__odoo_community__addons.items() %}
  {{ k8s__odoo_community__odoo_instance__addons_dir }}/{{ addon_name }}/{{ addon.url.split('/')[-1] }}{{ addon.repoSubpath }}
  {% if not loop.last %},{% endif %}
  {% endfor %}

#
k8s__odoo_community__odoo_instance__addons_paths: "{{ k8s__odoo_community__odoo_instance__addons_paths_ | regex_replace(' ', '') }}"
