---
k8s__odoo_community__namespace: odoo-mosellane
k8s__odoo_community__external_hostname: odoo-mosellane.{{ iac__root_domain }}

k8s__odoo_community__db__name: odoo-postgresql
#
k8s__odoo_community__db__config__db_name: odoo-db
k8s__odoo_community__db__config__admin_password: odoo-admin_PwD1231.L14d
k8s__odoo_community__db__config__username: odoo
k8s__odoo_community__db__config__password: odoo-blaBlA_PwD1231.LCC

#
k8s__odoo_community__add_server_definitions_into_pgadmin: false
