---
- name: Install ARC
  kubernetes.core.helm:
    name: arc
    chart_ref: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
    release_namespace: arc-systems
    create_namespace: true

# https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/authenticating-to-the-github-api
- name: Store secret
  kubernetes.core.k8s:
    state: present
    template:
      - path: "templates/ns.yml.j2"
      - path: "templates/secrets.yml.j2"

- name: Install action runners
  kubernetes.core.helm:
    name: arc-runner-set
    chart_ref: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set
    release_namespace: arc-runners
    create_namespace: false
    values:
      githubConfigUrl: "{{ github_org_url }}"
      githubConfigSecret: pre-defined-secret
