---
#
#
#

- name: Build Custom runner image and push it
  tags: [runner-set]
  community.docker.docker_image:
    state: present
    name: "{{ lar_docker_image_name }}"
    tag: latest
    build:
      path: "{{ role_path }}/files/local-runner-image"
    source: build
    repository: "{{ lar_repository_url }}"
    push: true

#
#
#

# https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/authenticating-to-the-github-api
- name: Setup namespace + GH App + Local Cache secrets
  tags: [runner-set]
  kubernetes.core.k8s:
    state: present
    template:
      - path: templates/runner-set/ns.yml.j2
      - path: templates/runner-set/gh-app-secrets.yml.j2
      - path: templates/runner-set/config.yml.j2

- name: Get ACTION CACHE URL
  tags: [runner-set, helm]
  register: gha_cache_url
  ansible.builtin.shell: |
    kubectl get secret gha-cache-access -n {{ github_arc_runners_ns }} -o jsonpath={".data.ACTIONS_CACHE_URL"} | base64 -d

- name: Install action runners set
  tags: [runner-set, helm]
  kubernetes.core.helm:
    name: arc-runner-set
    chart_ref: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set
    release_namespace: "{{ github_arc_runners_ns }}"
    create_namespace: false
    # https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set/values.yaml
    values:
      githubConfigUrl: "{{ github_org_url }}"
      githubConfigSecret: gh-app
      controllerServiceAccount:
        namespace: arc-systems
        name: arc-gha-rs-controller
      maxRunners: 5
      minRunners: 1
      containerMode:
        type: dind
      template:
        spec:
          containers:
            - name: runner
              image: "{{ lar_repository_url }}:latest"
              command: ["/bin/sh", "-c"]
              args: ["/home/runner/run.sh"]
              env:
                # using cleaner "envFrom[0].secretRef" prevents runners from spawning !
                - name: ACTIONS_CACHE_URL
                  value: "{{ gha_cache_url.stdout }}"
              # envFrom:
              #   - secretRef:
              #     name: gha-cache-access
              volumeMounts:
                - name: crt
                  mountPath: /etc/ssl/certs/ca-certificates.crt # only way to allow our CA to be acked for classic HTTPS calls
                  subPath: ca.crt
                - name: config
                  mountPath: /etc/buildkit/buildkitd.toml # also required
                  subPath: buildkitd.toml
          securityContext:
          volumes:
            - name: crt
              secret:
                secretName: "{{ org_ca_cert_secret_name }}"
            - name: config
              configMap:
                name: config
