---
- name: Log into private registry and force re-authorization
  community.docker.docker_login:
    registry_url: registry.kube-system
    username: "{{ registry_username }}"
    password: "{{ registry_password }}"
    reauthorize: true

- name: Build Custom runner image and push it
  community.docker.docker_image:
    state: present
    name: "{{ lar_docker_image_name }}"
    tag: latest
    build:
      path: "{{ role_path }}/files/local-runner-image"
    source: build
    repository: "{{ lar_repository_url }}"
    push: true

# https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/authenticating-to-the-github-api
- name: Setup namespace + GH App + Local Cache secrets
  kubernetes.core.k8s:
    state: present
    template:
      - path: templates/runners-set/ns.yml.j2
      - path: templates/runners-set/gh-app-secrets.yml.j2

- name: Install action runners set
  kubernetes.core.helm:
    name: arc-runner-set
    chart_ref: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set
    release_namespace: "{{ github_arc_runners_ns }}"
    create_namespace: false
    values:
      githubConfigUrl: "{{ github_org_url }}"
      githubConfigSecret: gh-app
      template:
        spec:
          containers:
            - name: runner
              image: "{{ lar_repository_url }}"
              command: ["/home/runner/run.sh"]
              envFrom:
                - secretRef:
                  name: gha-cache-access
