---
- name: Roundcube Create Persistent Volume dir path
  ansible.builtin.file:
    path: "{{ roundcube_pv_path }}"
    state: directory
    mode: '0755'

- name: Install Roundcube
  kubernetes.core.k8s:
    state: present
    template:
      - path: templates/ns.yml.j2
      - path: templates/roundcube/config-ssl-staging.yml.j2
      - path: templates/roundcube/pv.yml.j2
      - path: templates/roundcube/config.yml.j2
      - path: templates/roundcube/service.yml.j2
      - path: templates/roundcube/deploy.yml.j2
      - path: templates/roundcube/ingress.yml.j2
