---
- name: Create namespace
  kubernetes.core.k8s:
    state: present
    template:
      - path: 'templates/ns.yml.j2'

- name: Generate password hash for postmaster
  ansible.builtin.command: |
    kubectl run -n docker-mailserver -it --rm --restart=Never \
    --image ghcr.io/docker-mailserver/docker-mailserver:latest temp-docker-mailserver \
    -- /bin/bash -c 'doveadm pw -s SHA512-CRYPT -u {{ postmaster_email }} -p {{ vault_postmaster_password }}'
  register: postmaster_pw_hash
  changed_when: postmaster_pw_hash.rc != 0

- name: Put in dict
  ansible.builtin.set_fact:
    default_accounts_dict: >
      {
        "{{ postmaster_email }}": "{{ postmaster_pw_hash.stdout_lines[0] }}",
      }

# https://webmin.com/faq/#can-i-run-webmin-or-usermin-behind-reverse-proxy
- name: Create persistent volume local path path ALONG initial account definition. it does not erase other accounts :)
  ansible.builtin.lineinfile:
    path: "{{ path_to_config_folder }}/postfix-accounts.cf"
    regexp: "^#? *{{ item.key | regex_escape() }}|"
    line: "{{ item.key }}|{{ item.value }}"
    create: true
    mode: '0755'
  with_dict: "{{ default_accounts_dict }}"

# produces fact "ipify_public_ip"
- name: Get my public IP
  community.general.ipify_facts:

- name: Install Docker Mailserver
  kubernetes.core.k8s:
    state: present
    template:
      - path: 'templates/sc.yml.j2'
      - path: 'templates/mailserver/certificate.yml.j2'
      - path: 'templates/mailserver/pv.yml.j2'
      - path: 'templates/mailserver/config.yml.j2'
      - path: 'templates/mailserver/service.yml.j2'
      - path: 'templates/mailserver/deploy.yml.j2'
  vars:
    local_storage_class_name: local-storage
