---
# - name: Create namespace
#   kubernetes.core.k8s:
#     state: present
#     template:
#       - path: 'templates/ns.yml.j2'

# - name: Generate password hash for postmaster
#   ansible.builtin.command: |
#     kubectl run -n docker-mailserver -it --rm --restart=Never \
#     --image ghcr.io/docker-mailserver/docker-mailserver:latest temp-docker-mailserver \
#     -- /bin/bash -c 'doveadm pw -s SHA512-CRYPT -u {{ postmaster_email }} -p {{ vault_postmaster_password }}'
#   register: postmaster_pw_hash
#   changed_when: postmaster_pw_hash.rc != 0

# - name: Put in dict
#   ansible.builtin.set_fact:
#     default_accounts_dict: >
#       {
#         "{{ postmaster_email }}": "{{ postmaster_pw_hash.stdout_lines[0] }}",
#       }

# # https://webmin.com/faq/#can-i-run-webmin-or-usermin-behind-reverse-proxy
# - name: Create persistent volume local path path ALONG initial account definition. it does not erase other accounts :)
#   ansible.builtin.lineinfile:
#     path: "{{ path_to_config_folder }}/postfix-accounts.cf"
#     regexp: "^#? *{{ item.key | regex_escape() }}|"
#     line: "{{ item.key }}|{{ item.value }}"
#     create: true
#     mode: '0755'
#   with_dict: "{{ default_accounts_dict }}"


##
## Patch With PROXY Protocol
##

# - name: Add startup configuration for Proxy
#   ansible.builtin.template:
#     src: "templates/mailserver/proxy/config/{{ item }}.j2"
#     dest: "{{ path_to_config_folder }}/{{ item }}"
#     mode: '0755'
#   loop:
#     - dovecot.cf
#     - user-patches.sh

# - name: Create service to bypass PROXY protocol for in-cluster access
#   kubernetes.core.k8s:
#     state: present
#     template:
#       - path: 'templates/mailserver/proxy/service.proxy.yml.j2'

##
## Patch Nginx Ingress
##

# - name: Override proxy definition file
#   kubernetes.core.k8s:
#     state: present
#     template:
#       - path: 'templates/mailserver/proxy/ingress-tcp.yml.j2'

# - name: Restart ingress-nginx daemonset
#   ansible.builtin.command: kubectl rollout restart daemonset ingress-nginx-controller -n ingress-nginx
#   register: inc_reset
#   changed_when: inc_reset.rc != 0

# - name: Patch existing ingress service exposed ports
#   kubernetes.core.k8s:
#     state: patched
#     kind: Service
#     name: ingress-nginx
#     namespace: ingress-nginx
#     definition:
#       spec:
#         ports:
#           # original
#           - name: http
#             port: 80
#             targetPort: 80
#             protocol: TCP
#           - name: https
#             port: 443
#             targetPort: 443
#             protocol: TCP
#           # added
#           - name: smtp
#             port: 25
#             targetPort: 25
#             protocol: TCP
#           - name: submissions
#             port: 465
#             targetPort: 465
#             protocol: TCP
#           - name: submission
#             port: 587
#             targetPort: 587
#             protocol: TCP
#           - name: imap
#             port: 143
#             targetPort: 143
#             protocol: TCP
#           - name: imaps
#             port: 993
#             targetPort: 993
#             protocol: TCP

#
##
#

- name: Install Docker Mailserver
  kubernetes.core.k8s:
    state: present
    template:
      - path: 'templates/sc.yml.j2'
      - path: 'templates/mailserver/certificate.yml.j2'
      - path: 'templates/mailserver/pv.yml.j2'
      - path: 'templates/mailserver/config.yml.j2'
      - path: 'templates/mailserver/service.yml.j2'
      - path: 'templates/mailserver/deploy.yml.j2'
  vars:
    local_storage_class_name: local-storage
