---
- name: Get JWT Secrets
  tags: [terraform]
  kubernetes.core.k8s_info:
    kind: Secret
    name: "{{ argo_cd__jwt_tokens_secret }}"
    namespace: "{{ argo_cd__namespace }}"
  register: jwt_secrets

- name: Put JWT into variable
  ansible.builtin.set_fact:
    argocd_syncer_token: "{{ jwt_secrets.resources[0].data[argocd__account_for__github_syncer] }}"

- name: Add secrets and variables to specific Github organization repositories through their topic
  tags: [terraform]
  community.general.terraform:
    project_path: "{{ terraform_project_path }}/github-actions-repository-configure"
    force_init: true
    complex_vars: true
    variables:
      iac__github_organization: "{{ iac__github_org }}"
      github_token: "{{ ansible_github_var_secrets_pat }}"
      #
      config:
        repository_socket: "{{ harbor__internal_hostname__registry_v2 }}"
        repository_user: "{{ harbor__registry_username }}"
        cache_path: "{{ github_arc__buildkit__local_mount_path }}"
      #
      variables:
        github_arc__buildkit__remote_socket: "{{ github_arc__buildkit__remote_socket }}"
      #
      secrets:
        argocd_syncer_token: "{{ argocd_syncer_token }}"
