---
- name: Get Token Path
  tags: [terraform]
  ansible.builtin.set_fact:
    argocd_syncer_token_path: "{{ iac__generated_creds_dir }}/argocd-token.{{ argocd__account_for__github_syncer }}.txt"

- name: Add secrets and variables to specific Github organization repositories through their topic
  tags: [terraform]
  community.general.terraform:
    project_path: "{{ terraform_project_path }}/github-actions-repository-configure"
    state: present
    force_init: true
    complex_vars: true
    variables:
      iac__github_organization: "{{ iac__github_org }}"
      github_token: "{{ ansible_github_var_secrets_pat }}"
      #
      config:
        repository_socket: "{{ registry__hostname }}"
        repository_user: "{{ registry__default_push_user }}"
        cache_path: "{{ github_arc__buildkit__local_mount_path }}"
      #
      variables:
        github_arc__buildkit__remote_socket: "{{ github_arc__buildkit__remote_socket }}"
      #
      secrets:
        argocd_syncer_token: "{{ lookup('ansible.builtin.file', argocd_syncer_token_path) }}"
