---
- name: Run PipX w/ requisites 
  community.general.pipx:
    state: inject
    name: ansible
    inject_packages:
      - botocore
      - boto3

- name: Wait for the pod to be running state
  ansible.builtin.shell: |
    kubectl get pod myminio-pool-0-0 -n minio-tenant -o jsonpath='{.status.phase}'
  register: pod_status
  until: pod_status.stdout == "Running"
  retries: 10
  delay: 10

- name: Create default bucket
  amazon.aws.s3_bucket:
    access_key: "{{ minio_access_key_id }}"
    secret_key: "{{ minio_secret_access_key }}"
    #
    name: "{{ minio_tenant_backup_storage_bucket_name }}"
    endpoint_url: "{{ minio_tenant_s3_url }}" # HTTPS REQUIRED !
    validate_certs: false # ignore self signed certificates
    region: "{{ minio_tenant_backup_storage_bucket_region }}"
