---
- name: Run Pip w/ requisites
  ansible.builtin.pip:
    name:
      - botocore
      - boto3


- name: Wait for pod to become Ready
  ansible.builtin.command: |
    kubectl wait
    pod/myminio-pool-0-0
    --namespace=minio-tenant
    --for=condition=Ready
    --timeout=120s
  register: pods_ready
  changed_when: pods_ready.rc != 0

- name: Create default bucket
  amazon.aws.s3_bucket:
    access_key: "{{ minio_access_key_id }}"
    secret_key: "{{ minio_secret_access_key }}"
    #
    name: "{{ minio_tenant_backup_storage_bucket_name }}"
    endpoint_url: "{{ minio_tenant_s3_url }}" # HTTPS REQUIRED !
    validate_certs: false # ignore self signed certificates
    region: "{{ minio_tenant_backup_storage_bucket_region }}"
