- name: Create Persistent Volume dir path
  ansible.builtin.file:
    path: "{{ sentry_pv_path }}"
    state: directory
    mode: '0755'

### NOT AVAILABLE

# - name: Add stable chart repo
#   kubernetes.core.helm_repository:
#     name: sentry
#     repo_url: https://sentry-kubernetes.github.io/charts

- name: Set facts
  set_fact:
    tmp_path: /tmp/sentry_k8s
- name: Set facts
  set_fact:
    chart_path: "{{ tmp_path }}/sentry"
- name: Git clone
  ansible.builtin.git:
    repo: https://github.com/sentry-kubernetes/charts
    dest: "{{ tmp_path }}"
    version: sentry-v23.3.0
- name: helm build
  ansible.builtin.command:
    cmd: helm dependency build
    chdir: "{{ chart_path }}"

- name: Install Sentry w/ Helm
  kubernetes.core.helm:
    name: sentry
    chart_ref: "{{ chart_path }}" # sentry/sentry
    release_namespace: sentry
    create_namespace: true
    values:
      ingress:
        enabled: true
        ingressClassName: "{{ ingress_nginx_class }}"
        annotations:
          #   If you are using nginx ingress controller, please use at least those 2 annotations
          nginx.ingress.kubernetes.io/use-regex: "true"
        hostname: sentry.{{ root_domain }}
      service:
        type: LoadBalancer
      github: {}
