---
- name: Install Metrics Service Monitors
  kubernetes.core.k8s:
    state: present
    template:
      - path: 'templates/prometheus-services/servicemonitor-argocd-metrics.yml'
      - path: 'templates/prometheus-services/servicemonitor-argocd-repo-server-metrics.yml'
      - path: 'templates/prometheus-services/servicemonitor-argocd-server-metrics.yml'
