---
#
# https://argo-cd.readthedocs.io/en/stable/user-guide/private-repositories/#github-app-credential
#

- name: Search for pod exact name
  kubernetes.core.k8s_info:
    kind: Pod
    label_selectors:
      - app.kubernetes.io/name = argocd-server
  register: pod_name_search

- name: Fu
  vars:
    url_part: https://argocd-server.argocd/api/v1
  block:
    - name: Read keys as raw bytes
      ansible.builtin.slurp:
        src: "{{ argocd_admin_pwd_path }}"
      register: admin_pwd

    - name: Get ArgoCD authentication token
      ansible.builtin.uri:
        url: "{{ url_part }}/session"
        validate_certs: false
        method: POST
        body_format: json
        body:
          username: "admin"
          password: "{{ admin_pwd.content | b64decode }}"
      register: argocd_auth_response

    - name: Add repository to ArgoCD
      ansible.builtin.uri:
        url: "{{ url_part }}/repositories"
        validate_certs: false
        method: POST
        headers:
          Authorization: "Bearer {{ argocd_auth_response.json.token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          repo: "{{ argocd_repository_url }}"
          githubAppID: "{{ argocd_github_app_app_id }}"
          githubAppInstallationID: "{{ argocd_github_app_installation_id }}"
          githubAppPrivateKey: "{{ argocd_github_app_priv_key }}"


# https://argo-cd.readthedocs.io/en/stable/operator-manual/notifications/services/github/


#
# https://argo-cd.readthedocs.io/en/stable/operator-manual/notifications/services/github/
#
