---
##
## Interract with API, register repo and creds
##
- name: Read keys as raw bytes
  ansible.builtin.slurp:
    src: "{{ argocd_admin_pwd_path }}"
  register: admin_pwd
- name: Get ArgoCD authentication token
  ansible.builtin.uri:
    url: "{{ argocd_api_url_part }}/session"
    validate_certs: false
    method: POST
    body_format: json
    body:
      username: "admin"
      password: "{{ admin_pwd.content | b64decode }}"
  register: argocd_auth_response

- name: Add Github repository creds to ArgoCD
  ansible.builtin.uri:
    url: "{{ argocd_api_url_part }}/repocreds"
    validate_certs: false
    method: POST
    headers:
      Authorization: "Bearer {{ argocd_auth_response.json.token }}"
      Content-Type: "application/json"
    body_format: json
    body:
      type: "git"
      url: "{{ github_org_url }}"
      githubAppID: "{{ argocd_github_app_app_id }}"
      githubAppInstallationID: "{{ argocd_github_app_installation_id }}"
      githubAppPrivateKey: "{{ argocd_github_app_priv_key }}"

- name: Create auth token for Github Syncer
  block:
    - name: Generate new token
      register: syncer_token
      ansible.builtin.uri:
        url: "{{ argocd_api_url_part }}/account/{{ argocd_github_syncer_acc_name }}/token"
        validate_certs: false
        method: POST
        headers:
          Authorization: "Bearer {{ argocd_auth_response.json.token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          expiresIn: 0 # never expires
    - name: Make sure destination dir exists
      ansible.builtin.file:
        path: "{{ generated_creds_dir }}"
        state: directory
    - name: Save
      ansible.builtin.copy:
        content: "{{ syncer_token.json.token }}"
        dest: "{{ argocd_syncer_token_path }}"

- name: Add secrets to Github org
  community.general.terraform:
    project_path: "{{ terraform_project_path }}/gha-expose-secrets"
    state: present
    force_init: true
    complex_vars: true
    variables:
      github_organization: "{{ github_org }}"
      github_token: "{{ ansible_github_var_secrets_pat }}"
      #
      secrets:
        argocd_syncer_token: "{{ lookup('ansible.builtin.file', argocd_syncer_token_path) }}"

#
#
#

- name: Install ArgoCD notifications for Github
  block:
    # Download and apply manifest
    - name: Apply catalog
      ansible.builtin.command: |
        kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/notifications_catalog/install.yaml
    # https://argo-cd.readthedocs.io/en/latest/operator-manual/notifications/
    # https://argo-cd.readthedocs.io/en/latest/operator-manual/notifications/catalog/
    - name: Apply configuration and github secret (Controller wide, eg applies to all apps)
      kubernetes.core.k8s:
        state: present
        template:
          - path: templates/notifications/argocd-notifications-secret.yml.j2
          - path: templates/notifications/argocd-notifications-cm.yml.j2

#
#
#

- name: Install App of apps repository to ArgoCD
  tags: [apps, argocd]
  kubernetes.core.k8s:
    state: present
    template:
      - path: templates/apps/app-of-apps.yml.j2
