---
- name: Get Token Path
  ansible.builtin.set_fact:
    argocd_syncer_token_path: "{{ generated_creds_dir }}/argocd-token.{{ argocd_account_for_github_syncer }}.txt"

- name: Add secrets to Github org
  tags: [terraform]
  community.general.terraform:
    project_path: "{{ terraform_project_path }}/github-actions-repository-configure"
    state: present
    force_init: true
    complex_vars: true
    variables:
      github_organization: "{{ github_org }}"
      github_token: "{{ ansible_github_var_secrets_pat }}"
      #
      secrets:
        argocd_syncer_token: "{{ lookup('ansible.builtin.file', argocd_syncer_token_path) }}"
