- name: Apply configuration
  tags: [image-updater]
  kubernetes.core.k8s:
    state: present
    template:
      - path: templates/image-uploader/config.yml.j2

- name: Install Image Updater
  tags: [image-updater]
  command: |
    kubectl apply
    -n argocd
    -f https://raw.githubusercontent.com/argoproj-labs/argocd-image-updater/master/manifests/install.yaml
