- name: Install ArgoCD Image Updater w/ Helm
  tags: [helm, image-updater]
  kubernetes.core.helm:
    name: argocd-image-updater
    chart_ref: argo/argocd-image-updater
    release_namespace: argocd
    create_namespace: false
    wait: false
    values:
      config:
        registries:
          - name: Docker Hub
            prefix: docker.io
            api_url: https://registry-1.docker.io
            defaultns: library
          - name: Org Private Registry
            api_url: https://{{ registry_host }}
            prefix: "{{ registry_host }}"
            insecure: true
            default: true
