---
- name: ArgoCD setup
  ansible.builtin.import_tasks: setup.yml

- name: Handle credentials + Connect Github Org
  ansible.builtin.import_tasks: creds.yml

- name: Add secrets to GH
  ansible.builtin.import_tasks: creds.gh.yml

#
#

- name: Install Image Updater
  ansible.builtin.import_tasks: image-updater.yml

#
#

- name: Add default apps
  ansible.builtin.import_tasks: default-apps.yml
