subdomains_to_secure=[
    "webmin",
    "portainer",
    "k8s-dashboard",
    "vault",
    "graphana",
    "prometheus",
    "admin-ldap",
    "minio-console",
    "minio",
    "registry",
    "policy-reporter",
    "skooner"
]