---
- name: Install Webmin
  hosts: all
  become: true
  tasks:
    # https://webmin.com/download/#setup
    - name: Add key Webmin repository
      ansible.builtin.apt_key:
        url: https://www.webmin.com/jcameron-key.asc
        state: present

    - name: Add Webmin repository
      ansible.builtin.apt_repository:
        repo: 'deb https://download.webmin.com/download/repository sarge contrib'
        state: present
        filename: webmin
        update_cache: true

    - name: Install Webmin
      ansible.builtin.apt:
        name: webmin
        state: present # latest
        update_cache: true
        install-recommends: true
