---
- name: Read keys as raw bytes
  register: local_unseal_keys_raw
  ansible.builtin.slurp:
    src: "{{ k8s__hc_vault_unseal_keys_path }}"

- name: Load facts
  ansible.builtin.set_fact:
    unseal_keys: "{{ local_unseal_keys_raw.content | b64decode }}"

- name: Unseal
  loop: "{{ unseal_keys.unseal_keys_hex }}" # inject as array
  kubernetes.core.k8s_exec:
    namespace: "{{ k8s__hc_vault_namespace }}"
    pod: "{{ k8s__hc_vault_pod_name }}"
    command: vault operator unseal {{ item }}
