---
- name: Add stable chart repo
  kubernetes.core.helm_repository:
    name: hashicorp
    repo_url: https://helm.releases.hashicorp.com

- name: Create Persistent Volume dir path
  ansible.builtin.file:
    path: "{{ iac__pv_path__hc_vault }}/{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - data-vault-0

- name: Create Persistent Volumes + SSL certificates (injector, server)
  kubernetes.core.k8s:
    template:
      - path: templates/ns.yml.j2
      - path: templates/pv.yml.j2
      - path: templates/injector/certificate.yml.j2
  loop:
    - data-vault-0

- name: Install Zero-Trust configuration
  tags: [zto-app]
  kubernetes.core.k8s:
    template:
      - path: templates/caa.yml.j2

- name: Install Hashicorp Vault w/ Helm
  kubernetes.core.helm:
    name: vault
    chart_ref: hashicorp/vault
    release_namespace: "{{ k8s__hc_vault_namespace }}"
    values:
      global:
        enabled: true
        tlsDisable: true #

      injector:
        enabled: true
        leaderElector:
          enabled: false
        certs:
          secretName: injector-tls
        webhook:
          annotations:
            cert-manager.io/inject-ca-from: "{{ k8s__hc_vault_namespace }}/injector-certificate"

        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 256Mi
            cpu: 250m

      server:
        # These Resource Limits are in line with node requirements in the
        # Vault Reference Architecture for a Small Cluster
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
          limits:
            memory: 2Gi
            cpu: 1000m

        # extraEnvironmentVars is a list of extra environment variables to set with the stateful set. These could be
        # used to include variables required for auto-unseal.
        # extraEnvironmentVars:
        #  VAULT_CACERT: /vault/userconfig/tls-ca/ca.crt

        ingress:
          enabled: true
          ingressClassName: "{{ iac__ingress_nginx_class }}"
          annotations:
            # when using Cloudflare's proxied DNS record
            nginx.ingress.kubernetes.io/ssl-redirect: "false"
            cert-manager.io/cluster-issuer: "{{ cert_manager__org__issuer }}"
            nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
            #
            external-dns.alpha.kubernetes.io/hostname: "{{ k8s__hc_vault__external_hostname }}"
            external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
            #
            ingress-dashboard/title: Hashicorp Vault
            ingress-dashboard/description: Allow a robust and secure way to share secrets and private keys bewteen services
            ingress-dashboard/logo-url: /favicon.ico
            ingress-dashboard/assume-tls: "true"
            ingress-dashboard/hide: "false"
          hosts:
            - host: "{{ k8s__hc_vault__external_hostname }}"

        # extraVolumes is a list of extra volumes to mount. These will be exposed
        # to Vault in the path `/vault/userconfig/<name>/`.
        # extraVolumes:
        #   - type: secret
        #     name: tls-server
        #   - type: secret
        #     name: tls-ca
        #   - type: secret
        #     name: kms-creds

        standalone:
          enabled: true
          config: |
            ui = true

            listener "tcp" {
              tls_disable = 1
              address = "[::]:8200"
              cluster_address = "[::]:8201"
            }
            storage "file" {
              path = "/vault/data"
            }

        service:
          enabled: true
        auditStorage:
          enabled: false
        dataStorage:
          enabled: true
          storageClass: "{{ iac__local_storage__class_name }}"
      # Vault UI
      ui:
        enabled: true
        serviceType: "LoadBalancer"
        externalTrafficPolicy: "Local"
        # serviceNodePort: null
        # externalPort: 8200
