---
#
# https://github.com/siarheidudko/webmin-under-kubernetes-ingress (careful, tutorial is half-assed, THIS is definitively source of truth since it WORKS !)
#

# https://webmin.com/download/#setup
- name: Add OLD key Webmin repository
  ansible.builtin.apt_key:
    url: https://www.webmin.com/jcameron-key.asc
    state: present

- name: Add OLD Webmin repository
  ansible.builtin.apt_repository:
    repo: 'deb https://download.webmin.com/download/repository sarge contrib'
    state: present
    filename: webmin
    update_cache: true

- name: Install Webmin
  ansible.builtin.apt:
    name: webmin
    state: present # latest
    update_cache: true
    install-recommends: true

- name: Install Webmin as K8s Ingress + Service
  kubernetes.core.k8s:
    state: present
    template:
      - path: 'templates/ns.yml.j2'
      - path: 'templates/service.yml.j2'
      - path: 'templates/ingress.yml.j2'
      - path: 'templates/endpoints.yml.j2'

# https://webmin.com/faq/#can-i-run-webmin-or-usermin-behind-reverse-proxy
- name: Force redirect on Webmin to use k8s proxy
  ansible.builtin.lineinfile:
    path: /etc/webmin/miniserv.conf
    regexp: "^#? *{{ item.key | regex_escape() }}="
    line: "{{ item.key }}={{ item.value }}"
  with_dict:
    'redirect_ssl': 1
    'redirect_host': '{{ webmin_public_hostname }}'
    # TODO
    'bind': '{{ private_network_ip }}' # node1 ClusterIP
  register: webmin_miniserv_conf
  notify:
    - Restart webmin daemon

# https://webmin.com/faq/#can-i-run-webmin-or-usermin-behind-reverse-proxy
- name: Add FQDN to Webmin Trusted Websites
  ansible.builtin.lineinfile:
    path: /etc/webmin/config
    regexp: "^#? *{{ item.key | regex_escape() }}="
    line: "{{ item.key }}={{ item.value }}"
  with_dict:
    'referers': '{{ webmin_public_hostname }}'
  register: webmin_config
  notify:
    - Restart webmin daemon
